TEAM-FLASH/Toucheese-FE

- tsconfig.app.json
<br>
- tsconfig.app 파일 수정
<br>
> Conf: tsconfig 파일 수정

- .github/workflows/deploy.yml
> Version 0.0 : 2차 배포 테스트

- .github/workflows/deploy.yml
> Version 0.0 : 3차 배포 테스트

- .github/workflows/deploy.yml
- deploy.sh
> Version 0.0 : 4차 배포 테스트

- .github/workflows/deploy.yml
> Version 0.0 : 5차 배포 테스트

- .github/workflows/deploy.yml
> Version 0.0 : 6차 배포 테스트

- .github/workflows/deploy.yml
- deploy.sh
> Version 0.0 : 7차 배포 테스트

- .github/workflows/deploy.yml
> Version 0.0 : 8차 배포 테스트

- index.html
> Version 0.0: 10차 배포 테스트

- src/components/Button/Button.test.tsx
> #3
<br>
> 불필요한 import 삭제
<br>
> 공통컴포넌트 버튼 기능을 구현하고 test 환경을 구축한다

- .github/workflows/deploy.yml
> Version 0.0: 11차 배포 테스트

- .github/workflows/deploy.yml
> Version 0.0: 11차 배포 테스트

- .github/workflows/deploy.yml
> Version 0.0: 12차 배포 테스트

- public/img/icon-close-btn.svg
- src/components/Modal/Modal.tsx
- src/hooks/useModal.ts
- src/store/useModalStore.ts
> #9 
<br>
- 전체 사이즈 모달 구현 완료
<br>
> 모달 사용 예시 참고
```js
import Modal from '@components/Modal/Modal';
import useModal from '@hooks/useModal';
const Home = () => {
// 모달 사용 방법
const modal = useModal();
// 만약 모달을 2개 이상 사용한다면, 아이디 값 전달 필수 (기본값 : 1)
const modal2 = useModal(2); 
// 버튼을 여러개 사용해야 할 경우를 대비하여 배열로 전달 (버튼 한개여도 동일)
const buttons = [
{
text: '적용하기',
event: () => alert('xxx'),
},
{
text: '이동하기',
event: () => {
modal2.closeModal();
navigate('/');
},
},
];
return (
<>
{/* useModal로 선언한 modal.open() */}
<button type="button" onClick={() => modal.open()}>
모달 오픈1
</button>
{/* useModal로 선언한 modal2.openModal() */}
<button type="button" onClick={() => modal2.open()}>
모달 오픈2
</button>
{/* modal */}
<Modal title="첫번째 모달" buttons={buttons} size="full">
모달 내부에 …
```
> [S2] full size 모달 구현 완료

- public/img/icon-arrow-gray.svg
- src/components/Calendar/Calendar.tsx
> #38 
<br>
- 캘린더 기능 구현 완료
<br>
> [S2] 캘린더 구현 완료

- src/components/Button/Button.tsx
- src/pages/Home/Home.tsx
> #40 
<br>
> 공통 버튼 컴포넌트 medium, large && fit 인 경우 padding 추가 
<br>
> 공통 버튼 컴포넌트 UI를 수정한다.

- src/components/BookingSearchContainer/BookingSearchContainer.tsx
- src/components/ImageSwiper/ImageSwiper.tsx
- src/components/Studio/StudioItem.tsx
- src/components/Studio/StudioList.tsx
- src/pages/Home/Home.tsx
- src/types/types.ts
#5 
<br>
- searchParams decoding 함수 StudioList 내부로 이동
- StudioList 컴포넌트 메인 & 검색 페이지 공통으로 사용
- StudioItem에 이미지 슬라이드 추가
<br>
- @aksenmi `<StudioList>` 컴포넌트 사용법
`<StudioList mode="search/result" searchParams={searchParams} />`
> [S2] 스튜디오 아이템 이미지 슬라이드 추가

- src/components/FilterPriceSlide/FilterPriceSlide.tsx
- src/components/Navigator/ThemeNavigator.tsx
> ex) #59 
<br>
- vibeName 쿼리 파람으로 넘기는 기능 구현
<br>
> [S2] 필터링 기능 QA

- src/components/BottomSheet/BottomSheet.tsx
> #45 
<br>
- 바텀 시트 max-height값 수정
<br>
> Hotfix: 바텀 시트 max-height값 수정

- src/components/Filter/FilterTextSelector.tsx
- src/pages/Home/Home.tsx
> #40 
<br>
> 불필요한 코드 삭제
> 바텀시트 close 적용
<br>
> [S2] 바텀시트 내 셀렉트 정렬 버튼 기능을 구현한다

- src/components/Filter/FilterTextSelector.tsx
> #40 
<br>
> 삼항연산자 -> If문으로 수정
<br>
> [S2] 타입 에러를 수정한다

- src/components/Calendar/Calendar.tsx
- src/pages/Home/components/DateBottomSheet.tsx
- src/pages/Home/components/LocalDateSelectionModal.tsx
- src/store/useSelectTime.ts
> #69  
<br>
- 바텀시트에서 선택된 '날짜 및 시간'을 home의 params로 추가 (바텀시트 -> 모달 -> home)
- 바텀시트 내 날짜 및 시간 '초기화' 기능 구현
- 가독성 향상을 위한 달력 컴포넌트 함수 및 변수명 변경
<br>
> [S2] 선택된 날짜 및 시간 값을 바텀시트 -> 모달 -> home으로 전달 기능 구현

- src/components/BookingSearchContainer/BookingSearchContainer.tsx
- src/components/ServiceAvailability/ServiceAvailability.tsx
> ex) #82 
<br>
- 타입 오류 해결
- 버튼 사용 방법 변경으로 인한 수정
<br>
> Refactor : type 오류 수정 버튼 사용방법 변경으로 인한 수정

- index.html
- public/robots.txt
> ex) #86 
<br>
> 
- robots.txt 파일 작성 public
- 메타태그 추가로 seo 강화
<br>
> [S2] SEO 강화를 위한 메타 태그 수정 및 robots.txt 작성

- index.html
- src/components/ServiceAvailability/ServiceAvailability.tsx
> Version 0.0.1: Story2 작업물 배포

- package.json
- pnpm-lock.yaml
- src/components/Calendar/Calendar.test.tsx
- src/components/Calendar/Calendar.tsx
> #76 
<br>
- 테스트 코드 경로 변경으로 수정중인 파일 우선 PR
<br>
- `@testing-library/user-event` 패키지 추가하였으니 pnpm i 부탁드립니다!
> [S3] 캘린더 테스트 코드 작성중

- src/pages/Home/components/LocalDateSelectionModal.tsx
- src/pages/Home/components/LocationSelectionModal.tsx
> #77 
<br>
> Story2 검색 페이지 내 지역 선택 기능 구현
- 선택한 지역을 params에 전달되도록 기능 구현
- 적용하기 버튼과 초기화 버튼 UI 추가
- 선택한 지역 스타일 유지를 위해 useEffect로 초기값 설정
<br>
> [S3] 검색 페이지 내 지역 선택 기능을 구현한다

- src/components/Filter/FilterTextSelector.tsx
> #103 
<br>
> Story2 다른 필터링 요소 적용 후 정렬 필터링 적용시 기존 적용 필터링 요소 초기화 오류 수정
- 정렬 필터링 요소 선택시 URLSearchParams를 받아와 수정하는 방식으로 변경
<br>
> [S3] 정렬 필터링 기능을 수정한다

- src/components/Studio/StudioItem.tsx
#106 
<br>
- S2의 QA 사항 수정
- 스튜디오 아이템의 img 태그에 alt 속성을 추가
<br>
> [S3] 스튜디오 아이템의 img 태그에 alt 속성 추가

- src/components/CopyButton/CopyButton.tsx
> #102 
<br>
- 스튜디오 주소 복사하기 버튼 컴포넌트 구현
<br>
- css 임시입니다.
- 현재 공통 컴포넌트 CopyButton으로 들어가 있는데 스튜디오 위치 지도 구현되면 내부 코드로 바꾸도록 하겠습니다.
> [S3] 복사 버튼 컴포넌트 구현

- src/components/BackButton/BackButton.tsx
- src/pages/search/Search.tsx
- src/pages/search/SearchResult.tsx
> #110 
<br>
- 뒤로가기 버튼 공통 컴포넌트화
- navigate(-1) 기능 추가
<br>
> [S3] 뒤로가기 버튼 공통 컴포넌트로 기능 수정

- src/components/BottomSheet/BottomSheet.tsx
- src/components/Calendar/Calendar.tsx
- src/components/Modal/Modal.tsx
- src/pages/Home/Home.tsx
- src/pages/Home/components/LocalDateSelectionModal.tsx
- tests/Calendar.test.tsx
- tests/LocalDateSelectionModal.test.tsx
> #95 
<br>
- 캘린더 테스트 코드 작성 완료
- 지역 및 날짜 선택 모달 테스트 코드 작성 (파라미터 검증 미완)
- 모달, 바텀 시트 닫기 버튼 name 변경
- 바텀시트 중복 호출 개선
<br>
> [S3] 캘린더, 지역 및 날짜 선택 모달 테스트 코드 작성

- src/components/Navigator/StudioNavigator.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
- src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
- src/routes.tsx
#116 
<br>
- 메뉴 상세페이지, 리뷰 모아보기 페이지가 필요해 라우팅 추가 및 임시 컴포넌트 작성
- 상단 탭 구현 완료
<br>
- 상단 탭(StudioNavigator) 컴포넌트 불러오시면 되고 이상한 점 있으면 말씀해주세요.
- 상단 탭 사용법
- StudioNavigator에 스튜디오 id (`_id: string`) 값을 넘겨주셔야합니다.
- useParams를 이용해 주소창에서 _id를 가져오신다면 다음과 같이 타입 assertion이 필요합니다.
(useParams로 불러오는 _id 값이 `string | undefined`인데, `undefined`일 경우는 없기 때문에)
```ts
const { _id } = useParams() as { _id: string };
```
- 백엔드에서 넘어온 스튜디오 id를 사용하신다면 `string` 타입으로 형변환하여 보내주세요.
```tsx
return (
<>
<StudioNavigator _id={_id} />
</>
)
```
> [S3] 상단 탭 구현 완료

- src/components/Filter/Filter.tsx
- src/pages/Home/Home.tsx
- src/pages/Home/components/LocalDateSelectionModal.tsx
- src/pages/Home/components/LocationBottmSheet.tsx
> #111 
<br>
> 메인페이지에 적용된 필터링 버튼 기능 구현 완료
- params 값에 따른 필터링 버튼 활성화
- 필터링 선택 값 버튼 text에 동적 변경 적용
<br>
> [S3] 메인 필터링 버튼 활성화 기능을 구현한다

- src/components/BottomSheet/BottomSheet.tsx
#101 
<br>
-  바텀시트 컨텐츠 크기에 따른 동적 높이 변환
- 바텀시트 외의 다른 콘텐츠 클릭 시 바텀시트 닫기
- 바텀시트 드래그 닫기
<br>
> [S3] 바텀시트 드래그 기능 추가

- src/components/Filter/Filter.tsx
- src/pages/Home/Home.tsx
> #123 
<br>
> 메인에서 사용하는 reset 버튼 기능 적용
- reset 버튼 선택시 params 초기화 
<br>
> [S3] reset 버튼 기능을 구현한다

- src/components/Button/Button.tsx
- src/pages/Home/Home.tsx
> #127 
<br>
> 버튼 공통 컴포넌트의 스타일을 수정한다
- border 굵기 추가 
<br>
> [S3] 버튼 공통 컴포넌트의 스타일을 수정한다

- public/img/icon-chevronright.svg
- src/pages/Studio/StudioMenu/StudioMenu.tsx
- src/pages/Studio/StudioMenu/StudioMenuItem.tsx
- src/types/types.ts
#97 
<br>
- 메뉴 목록 UI 작업
- 메뉴 목록 데이터 통신
<br>
> [S3] 스튜디오 메뉴 목록 구현하다.

- src/components/Header/Header.tsx
> #110 
<br>
- 뒤로가기 버튼이 포함된 헤더 컴포넌트 구현
<br>
쓰다가 수정사항 있으면 말씀해주세요!
사용예시)
1. 특정 페이지 이동
`<Header title="리뷰 사진 모아보기" backTo="/home" /> `
2. 이전 페이지 이동
`<Header title="리뷰 사진 모아보기" /> `
3. title이 없을 경우
` <Header />`
4. 커스텀css 적용할 경우
`<Header customStyle={customStyle}/>`
> Feat: 헤더 컴포넌트 구현

- src/hooks/useGetStudios.ts
- src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
- src/types/types.ts
- tests/StudioList.test.tsx
- tests/useGetStudios.test.tsx
> #135 
<br>
- `완료` 
- `IStudioRes` 타입 활용을 위해 제네릭을 전달하도록 변경
- 스튜디오 상세 헤더 호출
- 네비게이션 호출
- 데이터 호출
- `미완료` 
- 메뉴 필터링 (API 수정 후 진행 가능)
- 포트폴리오 클릭시 딤 모달 처리
<br>
> [S3] 포트폴리오 페이지 진행중

- src/components/BottomSheet/BottomSheet.tsx
#145
<br>
- 바텀시트 이벤트 핸들러 수정
<br>
> [S3] 바텀시트 이벤트 핸들러 수정

- src/components/ImageSwiper/ImageSwiper.tsx
> #148 
<br>
- 한개용 이미지 슬라이드에 대한 너비 조정
- autoplay 기능 삭제
<br>
> [S3] 한개용 이미지 슬라이드 너비 조정

- src/pages/Studio/StudioMenu/StudioMenu.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
- src/pages/Studio/StudioMenu/StudioMenuItem.tsx
- src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
- src/types/types.ts
#156 
<br>
- 메뉴 상세 페이지 오타 수정
- 메뉴 상세 페이지 리뷰 컴포넌트 구현
- 컴포넌트 이동시 옵션 체크 버튼 유지
<br>
> [S3] 메뉴 상세보기 리뷰 컴포넌트 구현

- src/App.tsx
- src/components/Error/ErrorBoundary.tsx
- src/components/ImageSwiper/ImageSwiper.tsx
- src/pages/Home/Home.tsx
- src/pages/Studio/StudioReview/StudioReview.tsx
- src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
- src/pages/Studio/StudioReview/components/DropDown.tsx
- src/pages/Studio/StudioReview/components/ReviewContent.tsx
- src/pages/Studio/StudioReview/components/StudioReviewCategories.tsx
- src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
- src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
- src/routes.tsx
> ex) #152 
<br>
- SEO를 위한 헬멧 타이틀, 메타데이터 추가
- 성능 최적화를 위한 Lazy Import 추가 및 EB,SUSPENSE 등록
- 리액트 헬멧 적용 , 리뷰페이지 헬멧추가
- 드랍다운 변경 및 사진만 보기 삭제
<br>
> [S3] 리뷰 기능 고도화 , 성능 최적화를 위한 코드스플리팅, SEO를 위한 페이지내 헬멧 추가

- src/components/ImageSwiper/ImageSwiper.tsx
> ex) #169 
<br>
- 이미지 슬라이드 너비, 마진 수정
<br>
> [S3] 이미지 슬라이드 스타일 수정

- tests/Dimmedmodal.test.tsx
#143 
<br>
- 딤 모달 테스트 코드 작성
<br>
> [S3] 딤 모달 테스트 코드 작성

- src/pages/Studio/StudioMain/StudioMain.tsx
- src/types/types.ts
> #166 
<br>
- 스튜디오 상세정보 기능 구현 진행중
- 공유하기, 북마크 기능 Import 완료
- 해당 스튜디오 북마크 개수 데이터가 없는 오류로 이후 수정 필요
- 스튜디오 위치정보 Import 완료
- 스튜디오 매장정보 옵션 태그 추가
- 스튜디오 영업시간 타입 추가
<br>
> [S3] 스튜디오 상세정보 기능을 구현한다

- src/hooks/useGetStudioDetail.ts
- src/pages/Studio/StudioMain/StudioMain.tsx
- src/types/types.ts
- 갑작스러운 버그 수정
<br>
- 타입 변경으로 오류가 발생하여 수정하였습니다.
- `StudioItem`, `StudioDetail`에서 공통으로 사용할 수 있는 `StudioInfo` 타입을 생성하고 이를 `extends` 하였습니다.
<br>
> [S4] StudioItem, StudioDetail 타입 수정

- src/pages/Studio/StudioMain/StudioMain.tsx
- src/types/types.ts
> #166 
<br>
- 현재 접속 날짜를 영업중 여부와 비교하여 렌더링
- 정기휴무 기능 추가
- 공유, 북마크, 위치정보 import
<br>
> [S4] 스튜디오 상세정보 페이지 기능 구현 완료

- src/pages/Studio/StudioMain/StudioMain.tsx
> #166 
<br>
- 옵셔널체이닝 -> && 연산자로 수정
- key값을 index가 아닌 고유 id로 수정
- _id를 항변환 후 적용
<br>
> [S4] 스튜디오 상세정보 페이지의 오류를 수정한다

- src/pages/Reservation/components/PolicyModal.tsx
- src/styles/Common.tsx
#189 
<br>
- 개인정보처리방침 모달 구현 완료
- Typography 추가
<br>
- @aksenmi 필요하신 컴포넌트에서 다음과 같이 사용해주시면 됩니다!
```tsx
import useModal from '@hooks/useModal';
import PolicyModal from '@pages/Reservation/components/PolicyModal';
const ExampleComponent = () => {
const { open } = useModal(1);
return (
<>
…
<button onClick={() => {open()}}>버튼</button>
…
{/* 바깥쪽에서 컴포넌트 불러오기 */}
<PolicyModal />
</>
)
}
```
> [S4] 개인정보처리방침 모달 구현 완료

- src/components/Button/Button.tsx
- src/components/Filter/Filter.tsx
- src/pages/Home/Home.tsx
- src/pages/Studio/StudioMain/StudioMain.tsx
> #179 
<br>
- 버튼 공통 컴포넌트의 xsmall 사이즈 추가
- 메인페이지 필터 적용시 깨짐 현상 수정
- 메인페이지 필터 가로스크롤 적용
- 스튜디오 상세정보 스튜디오 옵션 버튼 사이즈 수정
<br>
- 기존 small 사이즈로 사용하던 요소보다 높이값 0.2rem 작고 폰트사이즈도 다른 xsmall 사이즈 버튼이 추가되었으니
피그마 시안 확인 하신 후에 기존에 적용하셨더 버튼 사이즈 타입 수정 부탁드립니다!
> [S4] 버튼 공통 컴포넌트의 스타일을 추가한다

- .github/workflows/deploy.yml
<br>
- 카카오 API KEY를 Secrets에 추가
<br>
> Version 0.1.1: Story 3 작업물 긴급 수정

- src/components/BackButton/BackButton.tsx
> #201 
<br>
카카오톡 공유시 뒤로가기 문제 수정
- 이전 기록이 없을 시 기본 경로로 이동하는 기능 추가
<br>
> [S4] 이전 기록이 없을 시 기본 경로 이동 

- src/pages/Home/Home.tsx
> #202 
<br>
- 필터 영역 백그라운드 컬러 삭제 오류 수정
- 필터 적용 후 가로스크롤 활성화 시 box-shadow 적용
<br>
> [S4] 메인페이지 필터링 영역의 백그라운드 컬러 오류를 수정한다

- src/pages/Reservation/ReservationComplete.tsx
- src/pages/Reservation/ReservationSchedule.tsx
- src/routes.tsx
#203 
<br>
- 예약 과정 라우팅 설정
- 예약 일정 컴포넌트 생성
<br>
```tsx
{
path: 'studio/:_id',
children: [
...
{
path: 'reservation',
children: [
{
index: true,
element: <ReservationSchedule />,
},
{
path: 'payment',
element: <ReservationCheck />,
},
{
path: 'complete',
element: <ReservationComplete />,
},
],
},
],
}
```
> [S4] 예약 과정 라우팅 설정

- .prettierrc.cjs
- src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
- src/styles/Variables.tsx
> #135
<br>
- 포트폴리오 목록 호출시 useQuery 적용
- 포트폴리오 목록 필터링 기능 구현
- 프리티어 printWidth 값 변경 : 200 -> 100
- 스타일 가이드 색상 추가 : red, green
<br>
- **스타일 가이드 색상이 추가**되었으니 활용 부탁드립니다 !
> [S4] 포트폴리오 필터링 구현 완료

- src/routes.tsx
<br>
- route 파일 내 `ReservationCheck` 이중 호출되어 변경
<br>
> [S4] ReservationCheck 이중 호출 오류 개선

- src/components/Kakao/KakaoMap.tsx
> #212 
<br>
- 지도보기 버튼 추가
- 지도보기 버튼 클릭시 카카오맵 연동으로 수정
<br>
> [S4] 지도보기 버튼 추가 및 경로 수정

- src/pages/Studio/StudioMain/StudioMain.tsx
> #208 
<br>
- 유저 접속 환경 webP 렌더링 지원 여부 확인 후 jpeg 형식의 파일을 webP 파일로 조건부 렌더링
<br>
> [S4] 스튜디오 상세정보 페이지 최적화 기능을 완료한다

- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
#222 
<br>
- 스튜디오 메뉴 상세페이지 이미지 스와이퍼 경로 수정
<br>
> [S4] 메뉴 상세페이지의 이미지 스와이퍼 경로를 수정한다.

- src/components/Button/Button.tsx
- src/pages/Studio/StudioMain/StudioMain.tsx
- src/pages/User/SignUp.tsx
> #220 
<br>
- 회원가입 페이지 UI 기능 구현 진행중
- 버튼 공통 컴포넌트 컬러 타입 추가 -> deepGray : gray500
<br>
> gray500 버튼 색상 타입 추가했습니다 deepGray 사용하시면 됩니다!
@s0zzang @woojoung1217 @JWJung-99 @kyungmim @aksenmi
> [S4] 회원가입 페이지 UI를 구현한다

- index.html
- src/pages/Reservation/ReservationCheck.tsx
- src/pages/Reservation/components/Payment.tsx
> #207 
<br>
- 이니시스 결제 기능 구현중
- 인풋창 포커스 기능 및 입력값 삭제 기능
- 체크박스 동의 여부 
<br>
> [S4] 이니시스 결제 기능 구현 및 인풋창 기능 추가

- src/components/Input/Input.tsx
- src/pages/User/Auth.tsx
- src/pages/User/LoginWithEmailPage.tsx
- src/pages/User/SignUp.tsx
> ex) #227
<br>
-  인풋 기능 호환성 업그레이드
- 
<br>
> [S4] 인풋 기능 수정 

- src/components/BottomSheet/BottomSheet.tsx
#224 
<br>
- 바텀시트 열렸을때 배경 layout shift 이슈 해결
- 모바일 화면 바텀시트 드래그시 새로고침되는 이슈 해결 (베포 후 확인해야함)
<br>
> [S4] 바텀시트 배경 layout shift 이슈 해결

- src/components/Button/Button.tsx
- src/pages/User/SignUp.tsx
> #220 
<br>
- 회원가입 페이지 UI 기능 구현 완료 
- 회원가입에서 사용되는 버튼 Gray 타입 추가
<br>
> [S4] 회원가입 페이지의 UI를 구현한다

- src/pages/Reservation/ReservationSchedule.tsx
> #216
<br>
- 결제 금액, 다음 버튼이 포함된 Reservation Footer 추가
<br>
> [S4] 예약 페이지 - ReservationFooter 추가

- src/pages/User/SignUp.tsx
> #232 
<br>
- 사용자 회원가입 간편 본인인증 기능 구현
- 회원가입 비밀번호 유효성 검사
<br>
> [S4] 사용자 회원가입 간편 본인인증 기능을 구현한다.

- src/components/Studio/StudioItem.tsx
#247 
<br>
- 스튜디오 주소가 길면 UI가 깨지는 현상 수정
<br>
> [S4] 스튜디오 주소가 길면 UI가 깨지는 현상 수정

- src/pages/Reservation/ReservationComplete.tsx
#249 
<br>
- 예약 완료 화면 스타일 수정
<br>
> [S4] 예약 완료 화면 스타일 수정

- src/components/ReservationFooter/ReservationFooter.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
- src/store/useReservationStore.ts
#236 
<br>
- 메뉴 예약하기전 로그인 유무 로직 구분(로그인 기능 완료 후 수정 예정)
- 공통 예약하기 버튼 disabled 색상 추가
- 옵션 선택한 메뉴 다른메뉴 접속 후 재접속시 checked상태 유지 이슈 해결
<br>
> [S4] 메뉴 예약하기 전 로그인 유무 로직 구분

- src/pages/User/SignUp.tsx
> #251 
<br>
- 본인인증 기능을 팝업창으로 출력
<br>
> [S4] 회원가입 페이지의 본인인증 기능을 팝업창으로 분류한다.

- src/pages/Reservation/ReservationCheck.tsx
- src/pages/Reservation/components/Payment.tsx
> #244
<br>
- 네이버페이 테스트 결제 구현중
- 날짜, 시간 가짜데이터 전역값으로 대체
<br>
> [S4] 네이버페이 테스트 결제 구현

- src/components/BottomSheet/BottomSheet.tsx
#257 
<br>
- 바텀시트 모바일 스크롤 이슈 해결
<br>
> [S4] 바텀시트 모바일 스크롤 이슈 해결

- src/pages/Home/components/LocalDateSelectionModal.tsx
> #213
<br>
- 변경된 날짜, 시간 컴포넌트에 맞춰 전달되는 값을 변경
- 선택된 지역이 params로 전달되지 않고 있어서 추가
<br>
> [S4] 스튜디오 필터링 : 선택된 날짜, 시간, 지역 전달

- index.html
- package.json
- pnpm-lock.yaml
- src/pages/User/Auth.tsx
- src/pages/User/KakaoCallback.tsx
- src/pages/User/LoginWithEmailPage.tsx
- src/routes.tsx
- src/styles/GlobalStyles.tsx
> ex) #238 
<br>
> 
-  라우트 변경 
-  카카오 콜백 함수 구현 
<br>
> [S4] 카카오 로그인을 위한 함수 구현 

- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
- src/store/useReservationStore.ts
#266 
<br>
- 메뉴 저장 위치  sessionStorage로 수정
- 예약 정보 img,기본가격 추가
<br>
- 결제까지 완료 후 SessionStorage 비우는 함수 한번 호출해주세요.
``` ts
const clearReservationInfo  = useReservationStore((state) => state.clearReservationInfo )
const handleReservationComplete = () => {
...결제하기 내용
clearReservationInfo (); // 저장된 예약 정보 지우기
};
```
> [S4] 메뉴 예약 정보 SessionStorage 저장 위치 수정

- src/pages/Studio/StudioReview/StudioReviewPhotos.tsx
- src/pages/Studio/StudioReview/components/ReviewSwiper.tsx
- src/pages/User/Auth.tsx
- src/pages/User/KakaoCallback.tsx
- src/pages/User/LoginWithEmailPage.tsx
- src/routes.tsx
- src/types/types.ts
> ex) #264 
<br>
-  리뷰 사진 모아보기 구현 (API 필드가 빠진게 있어서 나중에 요청 예정)
-  이메일 , 카카오 로그인  오류로 인해 작업 지연
<br>
> 작업 중 다른 요청이 들어와 이슈와 다르게 작업하게 돼 PR요청 합니다.
> [S4] 로그인 , 이메일 구현 중 리뷰 사진 모아보기 구현 완료

- index.html
- src/components/Calendar/Calendar.tsx
- src/components/Swiper/DimSwiper.tsx
- src/pages/Home/components/SelectTime.tsx
- src/pages/Reservation/ReservationSchedule.tsx
- src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
> #135 #216
<br>
- index 파일에 site_name 메타 태그 추가
- 포트폴리오 페이지 : 헬멧, 헤딩 태그 추가
- 예약하기 페이지 : 헬멧, 헤딩 태그 추가
<br>
> [S4] 헬멧 및 헤딩 태그 추가 - 포트폴리오, 예약하기

- src/components/ReservationFooter/ReservationFooter.tsx
- src/pages/Studio/StudioMenu/StudioMenu.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
- src/pages/Studio/StudioMenu/StudioMenuItem.tsx
#275 
<br>
- 메뉴 목록, 상세페이지 SEO 메타 태그 추가
- 메뉴 목록, 상세페이지 Heading태그 계층 구조 변경
<br>
> [S4] 메뉴 목록,상세페이지 SEO추가 및 Heading태그 수정

- src/store/useUserStore.ts
- src/types/types.ts
#262 
<br>
- User 전역 상태 추가 작업 중
> [S4] User 전역 상태 추가 작업 중

- src/pages/search/Search.tsx
- src/pages/search/SearchResult.tsx
#283 
<br>
- 검색 및 검색 결과페이지에 SEO 추가
<br>
> [S4] 검색 및 검색 결과페이지에 SEO 추가

- src/components/BookingSearchContainer/BookingSearchContainer.tsx
- src/pages/User/GoogleCallback.tsx
- src/pages/User/MyPage.tsx
- src/store/useUserStore.ts
- src/types/types.ts
- src/utils/getLocalStorageItem.ts
#262
<br>
- User 전역 상태 수정 => `persist`를 사용하여 로컬 스토리지에 저장
- 로컬 스토리지에서 `getItem`을 수행하는 유틸리티 함수 생성 (타입 안정성 강화 목적)
- 홈에서 `user` 정보가 있다면 <b>마이페이지(임시)</b>로, 없다면 **로그인/회원가입 페이지**로 이동하는 로직 추가
- User 타입을 다음과 같이 분리 
- `null` 값도 포함하는 기본 User 인터페이스(`IUser`)
- 백엔드 요청 성공 후 값을 가지고 있는 User 인터페이스(`IUserRes`)로 분리
<br>
- @woojoung1217 이메일 및 카카오 로그인 완료 후, 전역 상태에 저장하는 로직 추가 부탁드립니다!
```tsx
const setUser = useUserStore(state => state.setUser);
...
// handleLogin 함수의 `try` 문 내부에서
setUser(result);
...
```
> [S4] User 정보 로컬 스토리지에 저장

- src/pages/Reservation/components/Payment.tsx
> #286 
<br>
- ReservationFooter를 이용한 결제하기 버튼 구헌
- 결제하기 성공시 예약정보 초기화 하는 방식 제거
<br>
> [S4] 결제하기 버튼 구현

- public/sitemap.xml
- src/pages/User/Auth.tsx
- src/pages/User/LoginWithEmailPage.tsx
> ex) #288 
<br>
- 이메일 로그인 
- 로그인 상태 로컬 저장 및 전역상태 저장
- 토스트 사용 방법 변경 
- 사이트맵 구조 변경
<br>
> [S4] 이메일로  로그인 기능구현 완료

- src/components/ReservationFooter/ReservationFooter.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
- src/store/useReservationStore.ts
#290 
<br>
- 예약 정보 studioId => menuId로 변경
- 공통 예약하기 버튼 active 추가 
<br>
> [S4] 매뉴 상세페이지 QA를 진행한다.

- src/pages/Reservation/ReservationCheck.tsx
- src/pages/Reservation/components/Payment.tsx
> #298 
<br>
- 카카오페이 고정된 주문번호를 동적으로 변경
- 결제금액 실제 총금액으로 변경
- baseUrl 설정을 env 파일로 분리
<br>
> [S4] 카카오페이 결제시 고유 주문번호 수정

- src/pages/Studio/StudioMain/StudioMain.tsx
- src/pages/User/AuthVerification.tsx
- src/routes.tsx
> #300 
<br>
- 본인인증 경로 라우터 추가
- 스튜디오 메인 페이지 포트폴리오 프리뷰 선택시 포트폴리오 탭으로 이동 네비게이트 추가
- 스튜디오 메인 페이지 예약하기 버튼 선택시 메뉴 탭으로 이동 네비게이트 추가
- 회원가입 본인인증 ButtonActive 함수 간결화
<br>
> [S4] 스튜디오 메인페이지 네비게이트와 본인인증 라우터 추가

- src/pages/Home/Home.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
#293 
<br>
-  메뉴 상세페이지 로그인 유무 로직 추가
- 메인 페이지에서 session에 lastPage 저장되어있을시 저장된 path로 이동
<br>
> [S4] 메뉴 상세페이지 로그인 유무 로직 구분 추가

- src/store/useUserStore.ts
- src/types/types.ts
#297
<br>
- 로그아웃 시 localStorage에서 삭제
- 로그인 방식 타입 수정
<br>
> [S4] User 전역 상태 초기화 방법 변경

- src/pages/Reservation/ReservationCanceled.tsx
- src/pages/Reservation/ReservationDetail.tsx
- src/pages/Reservation/ReservationList.tsx
- src/routes.tsx
#306 
<br>
- 예약 정보, 상세, 취소 라우팅 추가
- 예약 정보 : `http://localhost:5173/reservation/list`
- 예약 상세 : `http://localhost:5173/reservation/1` (예약 id)
- 예약 취소 완료 : `http://localhost:5173/reservation/1/canceled`
<br>
- 라우팅 경로입니다.
```tsx
{
path: 'reservation',
children: [
{
path: 'list',
element: <ReservationList />,
},
{
path: ':_id',
children: [
{ index: true, element: <ReservationDetail /> },
{ path: 'canceled', element: <ReservationCanceled /> },
],
},
],
},
```
> [S5] 예약 정보, 상세, 취소 완료 라우팅 추가

- src/components/BookingSearchContainer/BookingSearchContainer.tsx
- src/pages/Home/components/LocalDateSelectionModal.tsx
- src/pages/Home/components/SelectTime.tsx
- src/pages/Reservation/ReservationSchedule.tsx
- src/store/useSelectDateStore.ts
- src/store/useSelectTimeStore.ts
#313 
<br>
- 선택된 날짜/시간 전역 값을 로컬 스토리지에 저장 (-> 세션에 저장되도록 다시 변경)
- 선택된 시간 전역 값 형식 변경 : Set 자료구조 -> 배열
- 예약하기 - 시간 선택 컴포넌트 하단 여백 추가
<br>
> [S5] 선택된 날짜 및 시간 전역 값을 세션 스토리지에 저장

- src/pages/User/BookmarkedStudios.tsx
- src/pages/User/ChangePassword.tsx
- src/pages/User/ChangeProfile.tsx
- src/pages/User/MyReviews.tsx
- src/pages/User/PasswordConfirm.tsx
- src/pages/User/Profile.tsx
- src/routes.tsx
#312 
<br>
- '/user/profile' 내 정보 관리 페이지
- '/user/profile/edit' 내 정보 수정 페이지
- '/user/profile/passwordConfirm' 비밀번호 확인 페이지
- '/user/profile/passwordChange' 비밀번호 수정 페이지
- '/user/myReviews' 나의 리뷰 페이지
- '/user/bookmarks' 나의 북마크(사진관) 페이지
<br>
> [S5] 마이페이지 라우팅 정보 추가 및 페이지 생성

- src/pages/User/Auth.tsx
- src/pages/User/KakaoCallback.tsx
> ex) #292 
<br>
- 카카오 콜백  로그인 구조 promise => try catch 형태로 변경
- 카카오 콜백 성공 시 navigate로 데이터를 전송하도록 변경 
<br>
> @HuiseonDev  님은 useLocation 사용으로 데이터를 받아 올 수 있어요! 참고 부탁 드립니다.
> [S4] 카카오 로그인 기능 구현 완료

- src/pages/Home/components/SelectTime.tsx
- src/pages/Reservation/ReservationSchedule.tsx
- src/store/useSelectDateStore.ts
- src/store/useSelectTimeStore.ts
#313
<br>
- 선택되지 않은 경우 - 오류 개선
- 초기화 기능 추가
- 정해진 날짜/시간 포맷 함수 개선 : Set -> 배열 반영
- 필터링 시 저장된 날짜 및 시간 초기화
<br>
> [S5] 선택된 날짜 및 시간 초기화, 선택되지 않은 경우 예외 처리

- src/pages/Reservation/ReservationCanceled.tsx
- src/pages/Reservation/ReservationComplete.tsx
- src/pages/Reservation/components/CompleteMessage.tsx
#307 
<br>
- 예약 완료 / 예약 취소 완료 UI 공통화
> [S5] 예약 완료/취소 UI 공통화

- src/pages/Reservation/ReservationCanceled.tsx
- src/pages/Reservation/ReservationComplete.tsx
- src/pages/Reservation/components/CompleteMessage.tsx
> [S5] 예약 완료 후 날짜, 시간 초기화

- src/pages/User/AuthVerification.tsx
- src/pages/User/SignUp.tsx
- src/store/useSignupStore.ts
> #231 
<br>
- 본인인증 기능 useEffect 리다이렉트 오류 해결
- 유저 데이터 저장소 localStorage -> sessionStorage 
- 회원가입 플로우 이메일 중복 확인 기능 구현 진행중
<br>
> [S5] 본인인증 기능 오류를 해결하고 이메일 중복 확인 기능을 구현한다.

- src/components/ReservationCard/RatingReview.tsx
- src/components/ReservationCard/ReservationCard.tsx
- src/pages/Reservation/ReservationList.tsx
- src/pages/User/MyPage.tsx
#306 
<br>
- 예약 리스트에서 예약 카드 적용
<br>
> [S5] 예약 카드 적용 테스트

- src/pages/Reservation/ReservationCheck.tsx
- src/pages/Reservation/ReservationDetail.tsx
- src/pages/Reservation/components/Payment.tsx
- src/store/useReservationStore.ts
> #329 
<br>
- 결제 API 연동
- 방문자 정보, 요청사항, 결제방법 전역상태에 추가
<br>
> [S5] 결제 API 연동 및 예약 정보 전역상태로 저장

- src/pages/Reservation/ReservationCheck.tsx
- src/pages/Reservation/components/Payment.tsx
> #337 
<br>
- 예약화면 라디오 버튼 스타일 변경
- 결제창 실제 값으로 변경
<br>
> [S5] 예약화면 라디오 버튼 UI 수정 및 결제창 실제 값 변경

- src/components/Input/Input.tsx
- src/pages/User/AuthVerification.tsx
- src/pages/User/SignUp.tsx
- src/pages/User/signupSuccess.tsx
- src/routes.tsx
- src/store/useSignupStore.ts
> #231 
<br>
- 이메일 회원가입 기능 구현 완료
- 이메일 중복 확인 검증 기능 구현 완료
- 이메일 회원가입 성공 페이지 기능 구현 완료
- input 공통 컴포넌트 error가 없을 시 isvalid 적용하도록 수정
- 회원가입 유저 정보 name => userName으로 수정
- signup Store 오타 수정
- 이메일 회원가입 성공 페이지 라우터 추가
- react-helmet 적용
<br>
> [S5] 이메일 회원가입 기능을 구현한다.

- src/pages/User/ChangeProfile.tsx
- src/pages/User/PasswordConfirm.tsx
- src/pages/User/Profile.tsx
> #328 
<br>
- 유저 정보관리 페이지 기능 구현 완료
- 유저 개인정보 변경 페이지 UI 기능구현 완료
- 유저 비밀번호 변경 페이지 UI 기능 구현 완료
<br>
> [S5] 유저 정보관리 페이지 UI구현 및 기능 구현을 완료한다

- src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
#353 
<br>
- 메뉴 상세페이지 input checkbox 구조 변경
<br>
> [QA1] 체크박스 공통 UI로 수정

- src/components/Studio/StudioItem.tsx
#361 
<br>
- 스튜디오 최저가의 천단위마다 쉼표 추가
<br>
> [QA1] 스튜디오 최저가의 천단위마다 쉼표 추가

- src/components/BookingSearchContainer/BookingSearchContainer.tsx
- src/components/Navigator/ThemeNavigator.tsx
- src/components/Studio/StudioList.tsx
- src/pages/Home/Home.tsx
#365 
<br>
- 메인화면 전체지역 섹션 부분의 여백 조정
<br>
> [QA1] 메인화면 전체지역 섹션 부분의 여백 조정

- src/pages/Reservation/ReservationList.tsx
#371 
<br>
- 예약 내역 헤더 높이 조정
<br>
> [QA1] 예약 내역 헤더 높이 조정

- src/pages/Reservation/ReservationCheck.tsx
> [QA1] 예약화면 여백 조정 및 요청사항 글자수 적용

- src/pages/Reservation/ReservationList.tsx
#373 
<br>
- 예약 내역 헤더의 box-shadow 삭제
<br>
> [QA1] 예약 내역 헤더의 box-shadow 삭제

- src/pages/Reservation/ReservationCheck.tsx
- src/pages/Reservation/ReservationNpayCallback.tsx
- src/pages/Reservation/components/Payment.tsx
- src/routes.tsx
> #382 
<br>
- 네이버페이 리다이렉트 핸들러 추가
<br>
> [QA1] 네이버페이 결제취소 및 실패 시 리다이렉트 로직 수정

- src/components/Calendar/Calendar.tsx
- src/components/Modal/Modal.tsx
- src/pages/Home/components/DateBottomSheet.tsx
- src/pages/Home/components/LocalDateSelectionModal.tsx
- src/pages/Home/components/SelectTime.tsx
- src/store/useSelectDateStore.ts
- src/store/useSelectTimeStore.ts
> [QA1] 날짜/시간 선택 모달 사용성 및 오류 개선

- src/pages/User/SignUp.tsx
- tests/SignUp.test.tsx
> #378 
<br>
- 회원가입 플로우의 비밀번호 연산 검증 로직 추가
- 회원가입 비밀번호 검증 성능 테스트 코드 작성
<br>
> [QA1] 회원가입 플로우의 비밀번호 검증 오류를 해결한다.

- src/pages/Home/Home.tsx
> #391 
<br>
- 필터링 reset 버튼 실행시 지역 및 날짜 params query key까지 reset 되어 버리는 문제 해결
- reset 버튼 실행시 애니메이션 적용
<br>
> [QA1] 메인페이지 필터링 리셋 버튼의 QA를 적용한다

- src/components/FilterPriceSlide/FilterPriceSlide.tsx
- src/components/Input/Input.tsx
- src/components/ServiceAvailability/ServiceAvailability.tsx
- src/hooks/useResetState.ts
- src/pages/Studio/StudioReview/StudioReview.tsx
- src/pages/Studio/StudioReview/components/DropDown.tsx
- src/pages/Studio/StudioReview/components/StarRating.tsx
- src/pages/Studio/StudioReview/components/StudioReviewCategories.tsx
- src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
- src/pages/User/Auth.tsx
> ex) #385 
<br>
-  커밋 메세지 참고
-  구글 시트에 있는 내용 우선적으로 수정 (API가 바뀌지 않으면 작업 못하는 내용이 있어서 다음 회의에 반영예정)
<br>
> [QA1] QA 윤우중 담당 부분 오류 수정 및 작업완료

- src/components/Modal/Modal.tsx
- src/pages/Home/components/DateBottomSheet.tsx
- src/styles/Common.tsx
- src/styles/GlobalStyles.tsx
#388 
<br>
- Refactor: 웹 폰트 로딩 방식 변경(기본 -> swap)
- Fix: 구분선으로 인해 생기는 가로 스크롤 방지
- Style: 날짜 및 시간 선택 모달 스타일 개선 (타이틀 추가) 
<br>
> [QA1] 공통 컴포넌트에 QA 반영

- src/components/BookingSearchContainer/BookingSearchContainer.tsx
- src/pages/Home/components/LocalDateSelectionModal.tsx
- src/pages/Home/components/LocationBottomSheet.tsx
> #395 
<br>
- 지역 선택 UI 버튼 스타일로 변경 ( 버튼 공통 컴포넌트 추가 후 공통컴포넌트로 적용 예정 )
- 지역 선택 params query value 수정 (ex. 강남 -> 강남구)
- 지역 선택 후 새로고침 시 선택한 지역이 입력 필드에서 사라지는 문제 해결
<br>
> [QA1] 지역선택 QA를 적용한다

- src/App.tsx
- src/hooks/useScrollToTop.ts
#398 
<br>
- 페이지를 이동하면 스크롤을 최상단으로 이동
<br>
> [QA2] 페이지 이동시 스크롤 최상단 이동

- src/pages/Home/components/LocationBottomSheet.tsx
- src/pages/User/Profile.tsx
> #404 
<br>
- 유저 회원가입 경로 분기처리 및 비밀번호 변경 버튼 조건부 렌더링
- 로그아웃 임시 텍스트 삭제
- 지역 선택 필터링 서울 전체 선택 시 params value 오류 수정
<br>
> [QA2] 마이페이지 회원정보 QA를 적용한다.

- src/components/Button/Button.tsx
> #406 
<br>
- 버튼 공통 컴포넌트 폰트 스타일 적용 오류 수정
<br>
> [QA2] 버튼 공통 컴포넌트의 QA를 적용한다

- src/pages/Studio/StudioMain/StudioMain.tsx
- src/pages/User/Profile.tsx
> #408 
<br>
- 브라우저 WebP 지원 여부와 무관하게 접근 불가 시 기본 이미지 출력
<br>
> [QA2] 스튜디오 상세페이지의 포트폴리오 이미지 오류 QA를 적용한다.

- src/components/Header/Header.tsx
- src/pages/Studio/StudioMain/StudioMain.tsx
> #410 
<br>
- header title 중앙으로 ui 수정
- 스튜디오 상세페이지 header 스크롤시 title 출력
- 스튜디오 상세페이지 스크롤시 navigator sticky 작업 완료. 이후 IntersectionObserver방식으로 수정 필요
- 휴무 데이터 유무에 따른 조건부 렌더링
- 스튜디오 소개 텍스트 길이에 따른 더보기 버튼 조건부 렌더링
<br>
> [QA2] 스튜디오 상세페이지 QA를 적용한다

- src/pages/Studio/StudioMain/StudioMain.tsx
> #410 
<br>
- scrollY 값 수정
<br>
> [Hotfix] 스튜디오 메인 페이지의 scrollY 값을 수정한다.

- src/components/Swiper/ImageSwiper.tsx
> #417 
<br>
- 이미지스와이퍼 슬라이드 시 왼쪽 여백 제거
왼쪽 여백 제거 후 슬라이드 시 오른쪽 여백이 생기는 추가 이슈 발생... !
해결예정
<br>
> [QA2] 슬라이드시 왼쪽 여백 제거

- src/pages/Home/components/LocalDateSelectionModal.tsx
#423 
<br>
- 지역 및 일시를 변경해도 하단 필터링(인기순, 가격, 매장정보) 파람스가 유지되도록 함
<br>
> QA2] 지역 및 일시 선택 모달 사용성 개선

- src/pages/Studio/StudioMenu/StudioMenu.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
- src/pages/Studio/StudioMenu/StudioMenuItem.tsx
#419 
<br>
- 메뉴 목록 레이아웃 수정
- 메뉴 목록 아이콘 교체
- 메뉴 상세페이지 공통 구분선 적용
- 메뉴 페이지 뒤로 가기 경로 수정
- 메뉴 상세페이지 tab sticky 적용
<br>
> [QA2] 메뉴 상세페이지 QA리스트를 적용한다.

- src/components/Swiper/DimSwiper.tsx
#387
<br>
- useEffect를 사용하여 나타난 시각적 깜빡임을 useLayoutEffect로 변경하여 개선함
<br>
> [QA2] 포트폴리오 딤모달에서 스와이프를 하면 깜빡이는 현상 개선

- src/pages/Reservation/ReservationDetail.tsx
- src/pages/Reservation/components/LocationModal.tsx
> [QA2] 예약상세 전화기능 및 위치 추가

- src/components/Calendar/Calendar.tsx
- src/components/Modal/Modal.tsx
- src/pages/Home/components/DateBottomSheet.tsx
- src/pages/Home/components/SelectTime.tsx
- src/pages/Reservation/ReservationSchedule.tsx
#388 
<br>
- 캘린더 하단 구분선 잘림 개선
- 모달 여백 변경 (2rem -> 1.6rem)
- 달력을 고정 비율로 유지하는 aspect-ratio 삭제
- 빌드 오류 개선 (사용하지 않는 import 삭제)
- 날짜/시간 선택 - 날짜를 선택하지 않고 시간을 선택한 경우 조건 처리
- 선택된 날짜에 해당하는 달력이 렌더링 되도록 변경
- 모바일 환경에서 스와이프로 월 변경 기능 추가
<br>
> [QA2] 공통 컴포넌트 관련 QA 반영

- src/pages/User/MyPage.tsx
#437 
<br>
- 마이페이지 가로 스크롤 제거
<br>
- **문제**  : Swiper의 스타일이 width: 100vw로 설정되어 있어서, DividerStyle의 가상 요소가 부모의 크기 보다 더 넓어졌고, 결국 가로 스크롤이 발생
- **해결**
``` ts
const CustomDividerStyle = css`
&::after {
width: 100%;
max-width: calc(100vw + (${variables.layoutPadding} * 2)); 
}
`;
```
마이페이지 컴포넌트에서 &::after의 width를 제한
> [QA2] 마이페이지 가로 스크롤 제거

- src/App.tsx
- src/pages/Reservation/ReservationNpayCallback.tsx
> #431 
<br>
- 
- 
<br>
@JWJung-99 
네이버페이 리다이렉트페이지 로딩 중복 문제 때문에 App페이지 코드 수정이 필요해서 고쳤는데 확인부탁드립니다~!
> [QA2] 네이버페이 결제 리다이렉트 시 로딩 중복 제거

- src/components/BottomSheet/BottomSheet.tsx
#443 
<br>
- 바텀시트 컨텐츠와 함께 드래그되는 이슈 해결
<br>
> [QA2] 바텀시트 컨텐츠와 함께 드래그되는 이슈 해결

- src/components/ReservationCard/ReservationCard.tsx
- src/pages/Studio/StudioMenu/StudioMenu.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
- src/pages/Studio/StudioMenu/StudioMenuItem.tsx
- src/pages/User/MyPage.tsx
- src/styles/GlobalStyles.tsx
#445 
<br>
- body 위쪽 padding 제거
- body padding 변화로 인한 메뉴 목록,상세페이지 UI 수정
<br>
@woojoung1217 @JWJung-99 @HuiseonDev @aksenmi @s0zzang 
프론트엔드분들 확인 부탁드립니다!
body padding 제거하고 레이아웃 많이 틀어졌으니까 현재 PR merge하면 참고해주세요!
> [QA2] body 위쪽 padding 제거 및 스튜디오 메뉴 페이지 UI 수정 

- src/pages/Home/Home.tsx
- src/pages/Reservation/ReservationList.tsx
#448 
<br>
- 홈화면 UI 수정
- 예약 내역 화면 UI 수정
<br>
> [WEB1] 상단 padding 제거로 인한 홈화면, 예약 내역 화면 UI 수정

- src/components/FilterPriceSlide/FilterPriceSlide.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
- src/pages/Studio/StudioReview/StudioReview.tsx
- src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
> ex) #434 
<br>
- 필터 프라이스 슬라이드 px 오류 수정
- 스튜디오 메뉴 에서 메뉴명 중복 제거를 위한 리뷰 컴포넌트 수정 
<br>
> [QA2]  필터 px 수정 및 스튜디오 리뷰 아이템 메뉴 내용 프롭 추가

- src/hooks/useBookmark.ts
- src/hooks/useGetReservationList.ts
- src/hooks/useGetStudios.ts
#461 
<br>
- 에러 바운더리 설정
- 스튜디오 조회
- 북마크 설정/해제
- 예약 내역 조회
<br>
> [WEB1] 에러 바운더리 적용

- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
#470 
<br>
- 스튜디오 메뉴상세페이지 가로스크롤 이슈 해결
<br>
> [QA2] 스튜디오 메뉴상세페이지 가로스크롤 이슈 해결

- src/components/Bookmark/Bookmark.tsx
- src/hooks/useBookmark.ts
- src/routes.tsx
#473
<br>
- 북마크 등록/해제 로직 수정
- `route.tsx` 파일 import 오류 수정
<br>
> [WEB1] 북마크 등록/해제 로직 수정

- src/components/NoPic/NoPic.tsx
#481 
<br>
- NoPic 컴포넌트 반응형 작업 완료
<br>
> [WEB1] NoPic 컴포넌트 반응형 작업 완료

- src/components/Modal/Modal.tsx
- src/styles/BreakPoint.tsx
#480 
<br>
- Style: 미디어 쿼리 변수 정의
- Style: 모달 반응형 작업
- Style: 모바일 전체 모달 스타일 조건문 수정
- Fix: 모달이 여러 개 열렸을 경우, 딤 배경 중복 개선
<br>
```tsx
export const mqMin = (point: string) => `@media (min-width: ${point})`;
export const mqMax = (point: string) => `@media (max-width: ${point})`;
```
```tsx
const CloseXBtnStyle = styled.button`
width: 2.4rem;
aspect-ratio: 1/1;
background: url(/img/icon-close-gray800.svg) no-repeat center / 1.6rem;
position: absolute;
z-index: 9;
⭐️ moMax(1023)까지 적용 : 모바일 전용
${mqMax(breakPoints.moMax)} {
right: 0;
}
⭐️ pc(1024)부터 적용 : 피씨 전용
${mqMin(breakPoints.pc)} {
right: ${variables.layoutPadding};
}
`;
```
> [WEB1] 반응형 변수 정의 및 모달 반응형 구현

- src/components/BookingSearchContainer/BookingButton.tsx
- src/components/BookingSearchContainer/BookingSearchContainer.tsx
- src/components/Button/Button.tsx
- src/components/Navigator/ThemeNavigator.tsx
- src/components/PCHeader/PCHeader.tsx
- src/components/SearchButton/SearchButton.tsx
- src/components/Studio/StudioItem.tsx
- src/components/UserButton/UserButton.tsx
- src/hooks/useScrollToTop.ts
- src/pages/Home/Home.tsx
- src/styles/BreakPoint.tsx
#456
<br>
- 홈화면 PC 반응형 작업중
<br>
> [WEB1] 홈화면 PC 반응형 작업중

- src/components/Swiper/ImageSwiper.tsx
- src/hooks/useGetReservationList.ts
#468 
<br>
- 이미지 스와이퍼 스타일 우선수위 클랙스 추가
- 예약내역 fetch 'RESERVED' 타입 추가
<br>
@aksenmi @JWJung-99 지민님,진욱님 확인 부탁드립니다.
> [QA2] 이미지 스와이퍼 스타일 우선순위 수정 및 예역내역  'RESERVED' 타입 추가

- src/components/Modal/Modal.tsx
- src/pages/Reservation/components/CancelModal.tsx
#485 
<br>
- 예약 취소 POST 구현중 - API docs 대기중
- 모달 내 버튼 prop 확장
<br>
> [S5] 예약 취소 구현중

- src/components/Modal/Modal.tsx
- src/pages/Home/components/DateBottomSheet.tsx
- src/styles/GlobalStyles.tsx
#488 
<br>
- 딤 영역 클릭시 모달 꺼짐
- 가로 스크롤 방지 - PC html overflow-x: clip 추가
- 모달 활성화 시 overflow 수정 (overflow: auto -> overflow-y: auto)
- 모달 종류에 따라 반응형 스타일 적용
- 일시 선택 모달에 반응형 스타일 적용
<br>
> [WEB1] 모달 사용성 개선 완료

- src/components/BookingSearchContainer/BookingSearchContainer.tsx
- src/components/Header/Header.tsx
- src/components/Modal/Modal.tsx
- src/pages/Home/Home.tsx
- src/pages/Reservation/components/Payment.tsx
> [WEB1] 빌드 오류 해결

- src/components/Swiper/ImageSwiper.tsx
- src/pages/Reservation/ReservationDetail.tsx
- src/pages/Reservation/components/CancelModal.tsx
- src/pages/Reservation/components/LocationModal.tsx
> #476 
<br>
- 모달아이디 추가
- 이미지 슬라이드 그라디언트제거
<br>
> [QA2] 모달 아이디 추가 및 스와이퍼 스타일 수정

- .github/workflows/deploy.yml
> [WEB2] 배포용 환경변수 변경

- src/pages/Studio/StudioMenu/StudioMenu.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
#507 
<br>
- 스튜디오 메뉴 목록, 메뉴 상세페이지 에러바운더리 적용
<br>
> [QA2] 스튜디오 메뉴페이지 에러 바운더리 적용

- src/pages/Reservation/ReservationCheck.tsx
- src/pages/Reservation/ReservationComplete.tsx
- src/pages/Reservation/ReservationDetail.tsx
- src/pages/Reservation/components/Payment.tsx
> #498 
<br>
- 예약상세 API 연동 (아직 응답은 제대로 안넘어오는중)
<br>
@JWJung-99 
결제 완료 화면 넘어갈 때 쿼리 파라미터를 통해 예약 아이디를 보냈고 완료 화면에서 해당 파라미터를 뽑아냈는데 수정할 거 있으면 말씀해주세요! 현재 네이버페이가 안돼서 카카오페이로 테스트 해주셔야 합니다.
@JWJung-99 @s0zzang 
예약상세화면에서 취소 신청일시랑, 취소 사유는 제가 어떻게 받아와야하는지 여쭤봅니다!
> [QA2] 예약상세페이지 API 연동

- src/components/Button/Button.tsx
- src/pages/Studio/StudioMain/StudioMain.tsx
- src/pages/User/AuthVerification.tsx
- src/pages/User/ChangePassword.tsx
- src/pages/User/ChangeProfile.tsx
- src/pages/User/PasswordConfirm.tsx
- src/pages/User/Profile.tsx
- src/pages/User/SignUp.tsx
> #477 
<br>
- 유저 정보 변경 기능 로직 구현 완료 (api 대기중)
- 유저 비밀번호 변경 로직 구현 완료 (api 대기중)
- 비밀번호 변경 전 유저 확인 플로우 기능 구현 완료
- 마이페이지 로그아웃 버튼 적용
- 유저 정보 수정 성공시 modal open
- 스튜디오 메인 로딩 컴포넌트 연결
<br>
> [QA2] 유저 정보 변경 기능 진행중

- src/components/Filter/Filter.tsx
- src/components/Filter/FilterSort.tsx
- src/pages/Home/Home.tsx
- src/store/useFilterStore.ts
- src/types/types.ts
> #520 
<br>
- 정렬 버튼 선택시 드롭다운 형태로 UI 구현
- 선택된 정렬 값 `useFilterStore`에 저장
<br>
> [WEB2] PC버전 메인페이지 스튜디오 정렬 기능을 구현한다

- src/components/Filter/FilterSort.tsx
- src/pages/Home/components/PCFilterWrapper.tsx
> #523 
<br>
- SortBy Filter component import
- params prop 전달
- 필터 초기화 기능에 sortBy 추가
<br>
> [WEB2] PC 버전 Studio 정렬 기능을 적용한다.

- src/components/Navigator/StudioNavigator.tsx
#519 
<br>
- PC 버전 StudioNavigator 작업 중
<br>
> Cont: PC버전 StudioNavigator 작업 중

- src/components/Masonry/Masonry.tsx
- src/components/Modal/Modal.tsx
- src/components/Swiper/DimSwiper.tsx
- src/pages/Studio/StudioPortfolio/PortfolioSwiper.tsx
- src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
#529
<br>
- PC Masonry 레이아웃 변경 (4개 -> 2개)
- 딤 모달 PC용 반영
<br>
> [WEB2] 포트폴리오 상세 PC 반응형 구현

- src/pages/Home/components/SelectTime.tsx
#535 
<br>
- 현재 시간과 비교하여, 지나간 시간 비활성화
<br>
> [QA2] 날짜/시간 선택시, 지나간 시간 비활성화

- src/components/Studio/StudioInfo.tsx
- src/pages/Studio/StudioMain/StudioMain.tsx
- src/pages/User/ChangePassword.tsx
- src/store/useStudioDataStore.ts
> #534 
<br>
- 스튜디오 상세정보 데이터를 Session Storage에 저장하는 스토어 생성
- 스튜디오 메인 페이지 스튜디오 상세정보 컴포넌트 분리 진행중
<br>
> [WEB2] 스튜디오 상세정보 데이터를 Session Storage에 저장한다

- src/pages/Home/Home.tsx
#540 
<br>
- PC 필터 영역 스크롤 수정
<br>
> [WEB1] PC 필터 영역 스크롤 수정

- src/components/Header/Header.tsx
- src/components/Header/PCHeader.tsx
- src/components/Navigator/StudioNavigator.tsx
#537 
<br>
- `StudioNavigator`의 box-shadow 제거
- `PCHeader` 하단 구분선 추가
- PC 화면에서 모바일용 `Header` 제거
<br>
> [WEB2] PC 버전 스튜디오 상세 고정 영역 작업 중

- src/components/Studio/StudioInfo.tsx
- src/components/Studio/StudioInfoDock.tsx
- src/components/Studio/StudioOptions.tsx
- src/pages/Studio/StudioMain/StudioMain.tsx
#537
<br>
- 스튜디오 상세 오른쪽 고정영역 작업 중
- `StudioOptions` 컴포넌트 분리
- `StudioInfo` 컴포넌트 수정
- `StudioMain` 마크업 구조 변경
<br>
> [WEB2] 스튜디오 상세 오른쪽 고정영역 작업 중

- src/pages/Reservation/ReservationDetail.tsx
- src/pages/Reservation/ReservationList.tsx
- tests/RecentSearches.test.tsx
#548
<br>
- 예약 내역, 예약 상세 에러 해결
<br>
> [WEB2] 빌드 에러 해결

- package.json
- pnpm-lock.yaml
- src/pages/User/LoginWithEmailPage.tsx
- src/types/wj-password-validator.d.ts
> ex) #533 
<br>
- wj-password-validator 설치 후 변경
- CSS 반응형 작업 진행 중
<br>
> git pull 이 후 pnpm install 진행 해주세요!
> [WEB2]  반응형 작업 진행 중, 유효성 검사 라이브러리 배포 후 변경

- src/pages/Studio/StudioMain/StudioMain.tsx
> #534 
<br>
- `navigator`의 mobile, pc 반응형 위치 적용
<br>
> [WEB2] 스튜디오 메인 페이지의 반응형 구조를 적용한다.

- src/components/Studio/StudioInfo.tsx
- src/components/Studio/StudioInfoDock.tsx
#537
<br>
- `StudioInfo` 컴포넌트의 로그 삭제
- `StudioInfoDock`의 `data`가 없는 경우 예외 처리
<br>
> [WEB2] 스튜디오 상세 오른쪽 영역 작업 중

- index.html
- public/robots.txt
- public/sitemap.xml
#546 
<br>
- `robots.txt` Disallow 설정
- `index.html`, `sitemap.xml` 주소 변경 (근데 `sitemap.xml` 의미가 없을 거 같아요)
<br>
> [Hotfix] 주소 변경으로 인한 환경설정 변경

- src/components/ReservationFooter/ReservationFooter.tsx
- src/components/Swiper/ImageSwiper.tsx
- src/pages/Studio/StudioMenu/StudioMenu.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
- src/pages/Studio/StudioMenu/StudioMenuItem.tsx
#527 
<br>
- PC버전 반응현 작업
- 메뉴 목록
- 메뉴 상세페이지
- 공통 예약 버튼
- 이미지 스와이퍼 단일 버전
<br>
@aksenmi 지민님! 이미지 스와이퍼 단일 이미지쪽 수정하였고 아래 코드 부분을 수정하였습니다! 확인해주시면 감사하겠습니다!
``` ts
// 이전 작업 코드
breakpoints={
768: {
slidesPerView: 5.5,
},
1280: {
slidesPerView: 7,
allowTouchMove: false,
mousewheel: false,
pagination: false,
},
}
// 수정 작업 코드
breakpoints={
slidesPerView === 1
? {}
: {
768: {
slidesPerView: 5.5,
},
1280: {
slidesPerView: 7,
allowTouchMove: false,
mousewheel: false,
pagination: false,
},
}
}
```
> [WEB2] 1차 스튜디오 메뉴 페이지 PC버전 구현

- src/components/Header/PCHeader.tsx
- src/components/Studio/StudioInfoDock.tsx
#456 
<br>
- PC 헤더 z-index 변경
<br>
> [WEB1] PC 헤더 z-index 변경

- src/components/Modal/Modal.tsx
- src/components/Swiper/DimSwiper.tsx
- src/pages/Reservation/components/CancelModal.tsx
#555
<br>
- 버튼 variant 타입 변경 - deepGray 삭제 / deepGray->black
- 배포 에러 방지 - 사용하지 않는 변수 삭제 및 로그 처리
<br>
> [WEB2] 버튼 컴포넌트 변경 내역 반영

- src/hooks/useGetReservationList.ts
#561
<br>
- 예약 내역 조회 Hook의 에러 수정
- (현재) `response`가 없으면 retry 3번 시도 후 에러 발생
- (수정) `response`가 없으면 retry하지 않고 `null`을 반환 -> 해당 컴포넌트에서 예외처리
<br>
> [Hotfix] 예약 내역 조회 Hook의 에러 수정

- src/components/Studio/StudioInfoDock.tsx
- src/pages/Reservation/ReservationCheck.tsx
- src/pages/Reservation/ReservationDetail.tsx
- src/pages/Reservation/components/PolicyModal.tsx
- src/pages/Studio/StudioDetailLayout.tsx
- src/pages/Studio/StudioMain/StudioMain.tsx
- src/pages/User/ChangeProfile.tsx
- src/pages/User/PasswordConfirm.tsx
- src/routes.tsx
#537 
<br>
- `route.tsx`에서 `<StudioMain />`, `<StudioMenu />`, `<StudioPortfolio />`, `<StudioReview /> 하위 요소`의 라우팅 구조를 분리함
- `<StudioDetailLayout />` 컴포넌트를 생성하여 오른쪽 고정 영역을 포함한 공통 레이아웃을 적용함
```tsx
const StudioDetailLayout = () => {
return (
<main
css={css`
${mqMin(breakPoints.pc)} {
display: flex;
gap: 1.6rem;
}
`}
>
<section
css={css`
${mqMin(breakPoints.pc)} {
flex-grow: 1;
}
`}
>
<Outlet />
</section>
{/* PC용 */}
<StudioInfoDock />
</main>
);
};
```
- `<StudioMain />`
<table>
<tr><th>PC</th><th>모바일</th></tr>
<tr><td><img width="1653" alt="image" src="https://github.com/user-attachments/assets/be3b550f-bfe4-494c-b028-20696bbed01f" /></td><td><img width="297" alt="image" src="https://github.com/user-attachments/assets/aa6641fc-e794-4065-b419-6e21d7b …
> [WEB2] 스튜디오 상세 오른쪽 고정 영역 적용 중

- pnpm-lock.yaml
- tests/Button.test.tsx
> #534 
<br>
- 테스트 코드 버튼 컴포넌트 variant prop 추가
<br>
> [WEB2] 버튼 테스트 코드 빌드 오류를 해결한다.

- .github/workflows/deploy.yml
> Version 0.5.0: WEB2 작업 내용 배포

- src/components/Header/PCHeader.tsx
- src/components/Search/SearchBar.tsx
- src/pages/Home/Home.tsx
#567 
<br>
- PC 헤더의 검색창 크기 변경
- 검색창 활성화 시 `input` 폰트 색상 변경
- `<Home />`의 검은색 탭 `z-index` 조정
<br>
> [WEB1] PC 헤더의 검색창 크기 변경

- src/pages/Reservation/components/PolicyModal.tsx
#570 
<br>
- PC 버전 개인정보처리방침 모달의 UI 변경
<br>
> [WEB3] PC 버전 개인정보처리방침 모달의 UI 변경

- src/components/Studio/StudioInfoDock.tsx
- src/pages/Studio/StudioDetailLayout.tsx
#565 
<br>
- 스튜디오 상세 오른쪽 영역 - 데이터 불러오기 로직 수정
=> `StudioDetailLayout`에서 `data` 호출 후 `sessionStorage`에 저장
<br>
@HuiseonDev 어제 말한 내용입니다. 작업 전 확인해주세요!
> [WEB2] 스튜디오 상세 오른쪽 영역 - 데이터 불러오기 로직 수정

- src/components/Share/ShareButton.tsx
- src/components/Share/ShareModal.tsx
- src/components/Share/ShareOptions.tsx
#569
<br>
- PC버전에서 스튜디오 공유하기 UI를 바텀시트 -> 모달로 변경
<br>
> [WEB2] PC버전에서 스튜디오 공유하기 UI를 바텀시트 -> 모달로 변경

- src/pages/Reservation/components/CompleteMessage.tsx
#568
<br>
- PC 버전 예약 완료 화면 구현
<br>
> [WEB3] PC 버전 예약 완료 화면 구현

- src/components/Studio/StudioItem.tsx
#566
<br>
- PC버전에서 `ImageSwiper` -> `img`를 포함하는 `div`로 변경 중
<br>
> [WEB1] 메인화면에서 Swiper로 인해 발생하는 에러 해결

- src/pages/Home/Home.tsx
#456 
<br>
- PC버전 홈화면 필터 영역의 z-index 수정 
<br>
> [WEB1] PC버전 홈화면 필터 영역의 z-index 수정

- src/components/Studio/StudioItem.tsx
- src/pages/Home/Home.tsx
#584 
<br>
- PC버전 StudioItem에서 발생하는 key 에러 해결
<br>
> [WEB1] PC버전 StudioItem에서 발생하는 `key` 에러 해결

- README.md
#582 
<br>
- README.md 작성 중
<br>
> [Docs] README.md 작성 중

- src/components/Modal/Modal.tsx
#577 
<br>
- 모달 zIndex 변경 : 99 -> 99999
<br>
> [WEB2] 모달 zindex 조정

- src/components/Input/Input.tsx
- src/pages/Studio/StudioReview/StudioReview.tsx
- src/pages/Studio/StudioReview/components/DropDown.tsx
- src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx
- src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
- src/pages/User/LoginWithEmailPage.tsx
> ex) #540 
<br>
- 리뷰 페이지 데이터 없을 시 예외처리 작업
- 리뷰 페이지 반응형 작업 
<br>
> [WEB2] 리뷰 페이지 예외처리 및 반응형 작업 

- src/pages/Home/components/LocalDateSelectionModal.tsx
- src/pages/Home/components/LocationBottomSheet.tsx
- src/pages/Home/components/LocationModal.tsx
- src/pages/Home/components/LocationSelector.tsx
- src/pages/Studio/StudioMain/StudioMain.tsx
> #603 
<br>
- 지역 필터링 locationSelector 컴포넌트 분리 및 모달과 바텀시트에 적용
- 지역 필터링 컴포넌트 접근 환경별 조건부 렌더링
<br>
> [WEB3] 지역 필터링 UI 모달/바텀시트 조건부 렌더링 및 공통 컴포넌트 분리

- src/pages/Studio/StudioMain/StudioMain.tsx
> #605 
<br>
- studioDetail 데이터 비동기 로딩 처리로 세션 데이터 누락 문제 수정
<br>
> [WEB3] 스튜디오 메인 페이지의 데이터 누락 문제 해결

- src/components/Button/Button.tsx
> #607 
<br>
- 버튼 공통 컴포넌트 lightGray 컬러 추가
<br>
> lightGray 컬러 스타일이 추가되었습니다! 피그마 확인하시고 버튼 컴포넌트 스타일 수정 부탁드려요!
> <img width="756" alt="image" src="https://github.com/user-attachments/assets/6d1da364-5ddc-47bd-b778-401d49ef9fba" />
@woojoung1217 @JWJung-99 @aksenmi @s0zzang @kyungmim
> [WEB3] 버튼 공통 컴포넌트의 색상 스타일을 추가한다

- src/pages/Studio/StudioMain/StudioMain.tsx
> #609 
<br>
- 텍스트 overflow 여부를 기준으로 더보기 버튼 동적 렌더링
<br>
> [WEB3] 텍스트 길이에 따른 더보기 버튼의 조건부 렌더링 처리를 한다.

- src/pages/Reservation/ReservationDetail.tsx
> #613 
<br>
예약 상세 화면이 안보여지는 문제 해결
- API HTTP 메서드 GET에서 POST로 변경
<br>
> [WEB3] 예약상세API HTTP 메서드 변경

- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
- src/pages/User/MyPage.tsx
#611 
<br>
- 마이페이지 pc버전 적용
- 예약내역 지난날짜 필터링
- 스튜디오 메뉴 상세페이지 top 위치 수정
<br>
> [WEB3] 마이페이지 PC 반응형 적용

- src/components/Modal/Modal.tsx
- src/pages/Reservation/ReservationDetail.tsx
- src/pages/Reservation/components/CancelModal.tsx
> [WEB3] 예약 취소 POST 구현

- index.html
- src/components/Kakao/KakaoMap.tsx
- src/pages/Reservation/ReservationDetail.tsx
- src/pages/Reservation/components/LocationModal.tsx
- src/pages/Reservation/components/Payment.tsx
> #615 
<br>
- 예약상세 PC화면 구현중
<br>
> [WEB3] 예약상세 PC화면 구현

- src/components/Navigator/StudioNavigator.tsx
- src/pages/Studio/StudioDetailLayout.tsx
- src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx
#623
<br>
- 스튜디오 상세 탭 공통 적용 - PC 반응형에서 모바일 전용 탭 미노출
- 포트폴리오 상단 여백 반응형 처리
<br>
@woojoung1217 @HuiseonDev @aksenmi @kyungmim 
아래 내용을 일괄 처리하였습니다. 각 페이지에서 따로 처리하지 않아도 되며, 디자인상 표기된 PC 여백만 맞춰주세요 !
> [WEB2] 스튜디오 상세 탭 공통 적용 - PC 반응형에서 모바일 전용 일괄 미노출

- src/components/Bookmark/Bookmark.tsx
- src/hooks/useBookmark.ts
- src/hooks/useGetStudios.ts
#620
<br>
- 홈화면 북마크 적용 완료
<br>
> [S2] 홈화면 북마크 적용 완료

- src/components/Modal/Modal.tsx
- src/components/Swiper/DimSwiper.tsx
- src/pages/Home/components/DateBottomSheet.tsx
- src/pages/Home/components/LocalDateSelectionModal.tsx
- src/pages/Home/components/LocationBottomSheet.tsx
- src/pages/Home/components/LocationModal.tsx
- src/pages/Studio/StudioReview/components/ReviewSwiper.tsx
#631
<br>
- 모달 zIndex 변경 (99999 -> 99)
- 초기화 버튼 색상 일괄 변경 : 메인 지역/일시 필터링
- 딤모달 전용 스와이퍼 버튼 위치 조정
- 스와이퍼 버튼 노출을 위한 overflow 변경, 딤 스와이퍼 전용 스타일 개선(block -> grid)
- 리뷰 딤 스와이퍼 반응형 적용
<br>
> [WEB2] 리뷰 모달 반응형 구현 및 딤모달 스타일 개선

- README.md
> [Docs] README.md 파일 수정

- src/components/Studio/StudioItem.tsx
- src/pages/Home/Home.tsx
#637 
<br>
- PC버전 홈화면 필터 - 스튜디오 목록 간격 수정
- 홈화면 스튜디오 사진 PC버전은 7개까지 수정
<br>
> [WEB1] PC버전 홈화면 필터 - 스튜디오 목록 간격 수정

- src/components/BackButton/BackButton.tsx
- src/components/Navigator/BookmarkNavigator.tsx
- src/hooks/useGetBookmarkList.ts
- src/pages/User/BookmarkedStudios.tsx
- src/pages/User/components/BookmarkStudioItem.tsx
#641 
<br>
- 찜한 사진관 UI 작업 중
- 찜한 사진관 헤더 작업
- 찜한 사진관 테마 탭 구현 (기존 `ThemeNavigator`와는 로직이 달라 새로 작업하였습니다.)
- 모바일 헤더 뒤로가기 버튼 영역 수정
<br>
> [S5] 찜한 사진관 UI 작업 중

- src/components/ReservationCard/RatingReview.tsx
- src/pages/Reservation/ReservationDetail.tsx
> [WEB3] 이용완료 및 예약취소 PC 화면 구현

- src/components/Bookmark/Bookmark.tsx
- src/components/Studio/StudioInfo.tsx
- src/components/Studio/StudioItem.tsx
- src/hooks/useGetBookmarkList.ts
- src/pages/User/BookmarkedStudios.tsx
- src/pages/User/components/BookmarkStudioItem.tsx
- src/pages/User/components/BookmarkedStudioItem.tsx
- src/pages/User/components/BookmarkedStudioList.tsx
#641 
<br>
- 찜한 사진관 페이지 작업 완료
<br>
> [S5] 찜한 사진관 페이지 작업 완료

- src/pages/User/BookmarkedStudios.tsx
#641 
<br>
- 찜한 사진관 상단 패딩 수정
<br>
> [S5] 찜한 사진관 패딩 수정

- src/pages/Home/Home.tsx
#662 
<br>
- 홈 화면에서 PC → 모바일로 변경 시 `setIsFixed`의 상태 변경
|변경 전|변경 후|
|:--:|:--:|
|<img src="https://github.com/user-attachments/assets/91127d2a-e549-4dc5-babd-b4c4f8c1ae22" />|<img src="https://github.com/user-attachments/assets/29a16469-4d87-4e3d-8ce6-2f08cb491506" />|
<br>
> [QA] 홈 화면에서 PC → 모바일로 변경 시 `isFixed`의 상태 변경

- src/components/Bookmark/Bookmark.tsx
- src/components/Navigator/BookmarkNavigator.tsx
- src/components/Navigator/ReservationNavigator.tsx
- src/components/Navigator/StudioNavigator.tsx
- src/components/Navigator/ThemeNavigator.tsx
- src/components/NoPic/NoPic.tsx
- src/components/Studio/StudioItem.tsx
- src/components/Toast/Toast.tsx
- src/pages/User/components/BookmarkedStudioItem.tsx
#656
<br>
- 너무 작은 `rem` 단위를 `px`로 변경
<br>
> [QA] 너무 작은 `rem` 단위를 `px`로 변경

- src/pages/Reservation/ReservationCanceled.tsx
- src/pages/Reservation/ReservationComplete.tsx
- src/pages/Reservation/ReservationList.tsx
- src/pages/User/BookmarkedStudios.tsx
- src/pages/User/MyPage.tsx
#654
<br>
- React-Helmet 태그 추가
- 마이페이지
- 찜한 사진관
- 예약 내역
- 예약 완료 / 예약 취소 완료
<br>
> [QA] React-Helmet 추가

- src/pages/User/MyPage.tsx
- src/pages/User/PasswordConfirm.tsx
> #664 
<br>
- 불필요한 import 삭제
- 복호화된 이메일값으로 api 요청
<br>
> [Hotfix] 복호화된 유저 이메일을 사용한 비밀번호 변경 요청 처리

- src/components/NoResult/NoResult.tsx
#672 
<br>
- 스튜디오 조회 결과 없음 페이지 여백 수정
<br>
> [QA] 스튜디오 조회 결과 없음 페이지 여백 수정

- src/pages/Reservation/ReservationDetail.tsx
- src/pages/Reservation/components/Payment.tsx
> #670 
<br>
- 배포환경에서 카카오페이 결제가 안넘어가는 문제
-> 포트원 카카오페이 pg사 추가
<br>
@JWJung-99 
배포 후에 잘 작동이 되는지 확인이 필요합니다!
> [QA] 포트원 카카오페이 결제 pg사 명시

- src/components/Header/PCHeader.tsx
- src/components/ServiceAvailability/ServiceAvailability.tsx
#672
<br>
- `ServiceAvailability` 컴포넌트 로그 삭제
<br>
> [QA] 매장정보 로그 삭제

- src/components/Calendar/Calendar.tsx
- src/components/Modal/Modal.tsx
- src/hooks/useTabFocus.ts
- src/pages/Home/components/SelectTime.tsx
- src/styles/GlobalStyles.tsx
#652
<br>
- focus-visible 상태 스타일 개선 - outline 추가, border 색상 변경
- 탭 포커스 훅 정의
- 달력, 시간 선택 컴포넌트 - focusable 상태 개선
- 모달 - 탭 포커스 훅 적용, 닫기버튼 최하단으로 이동
<br>
> [웹접근성] 탭 포커스 개선 - focus-visible 상태 스타일 개선, 모달/달력/시간 선택 컴포넌트 개선

- src/pages/Reservation/components/PolicyModal.tsx
#675 
<br>
- 약관 동의 모달에 하단 여백 추가
<br>
> [QA] 약관 동의 모달에 하단 여백 추가

- src/components/ReservationFooter/ReservationFooter.tsx
- src/pages/Studio/StudioDetailLayout.tsx
#687
<br>
- (Hotfix) 스튜디오 상세 로직 변경
- 예약하기 푸터 z-index 수정
<br>
> [QA] 예약하기 푸터 z-index 수정

- src/components/Modal/Modal.tsx
- src/components/Share/ShareModal.tsx
- src/pages/Home/components/DateBottomSheet.tsx
- src/pages/Home/components/LocalDateSelectionModal.tsx
#691 
<br>
- 모바일 버튼 간격 수정
- 모바일 fullscreen 콘텐츠 레이아웃 변경
- additionalStyle prop 추가
- "초기화" 클릭시 바로 적용
- PC용 maxWidth 제거
- additionalStyle 전달
<br>
> [QA] 모달 QA 반영

- src/components/BookingSearchContainer/BookingButton.tsx
- src/hooks/useTabFocus.ts
- src/pages/Home/components/LocalDateSelectionModal.tsx
#652
<br>
- 모달 활성화시 탭 포커스 오류 개선중
- 모달 활성화 버튼에 data-focus 값 추가
<br>
> [웹접근성] 모달 내 버튼 keydown 이벤트 발생시 포커스 오류 개선중

- src/components/Studio/StudioItem.tsx
#672
<br>
- `StudioItem` 스타일 수정
- 아이콘 크기 수정
- 폰트 크기 수정
<br>
> [QA] StudioItem 폰트 및 아이콘 크기 수정

- src/components/ReservationFooter/ReservationFooter.tsx
- src/pages/Reservation/ReservationSchedule.tsx
#687
<br>
- 예약하기 푸터 padding 수정
- 그에 따라 ReservationSchedule 컴포넌트에 negative margin 추가
<br>
> [QA] 예약하기 푸터 padding 수정

- src/components/Studio/StudioInfo.tsx
- src/hooks/useGetStudioDetail.ts
- src/hooks/useGetStudios.ts
- src/types/types.ts
#620 
<br>
- 스튜디오 상세 조회 시 북마크 여부 반영 
<br>
> [S2] 스튜디오 상세 조회 시 북마크 여부 반영

- src/components/Studio/StudioItem.tsx
- src/pages/Home/Home.tsx
#672 
<br>
- `StudioItem` 탭 포커스 개선
<br>
> [QA] StudioItem 탭 포커스 개선

- src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
- src/pages/Studio/StudioMenu/StudioMenuItem.tsx
#699 
<br>
- 스튜디오 메뉴 상세 리뷰탭 width 크기 수정
- 마지막 리뷰 구분선 제거
- 메뉴 목록 설명 부분 데스트탑 폰트 크기 적용
<br>
> [QA] 스튜디오 메뉴 QA 반영

- src/components/Header/PCHeader.tsx
#704
<br>
- PC 헤더의 z-index를 수정해 기존에 발생한 스튜디오 상세 UI와의 겹침 문제 해결
|기존|수정|
|:--:|:--:|
|<img alt="image" src="https://github.com/user-attachments/assets/2bf05636-18f9-4c16-96df-bea1551becd5" />|<img  alt="image" src="https://github.com/user-attachments/assets/15940151-e25e-4618-8436-39caaafe4793" />|
<br>
> [QA] PC 헤더의 z-index 수정

- src/pages/Studio/StudioDetailLayout.tsx
- src/pages/Studio/StudioMain/StudioMain.tsx
> #710 
<br>
- 스튜디오 메인 페이지 로딩 컴포넌트 big -> small로 수정
- 스튜디오 메인페이지 포트폴리오 미리보기 기능 margin 값 변수값으로 수정
<br>
> [QA] 스튜디오 메인페이지의 UI를 수정한다.

- src/components/Bookmark/Bookmark.tsx
- src/components/Studio/StudioItem.tsx
- src/components/Studio/StudioList.tsx
- src/pages/Home/Home.tsx
#672 
<br>
- 스튜디오 아이템에서 `p` 태그 내부에 위치한 `h3` 태그로 인해 발생하는 에러 해결
- `p` 태그 자체를 `h3` 태그로 변경
- 스튜디오 리스트 최하단 스타일 오류 해결
|변경 전|
|:--:|
|<img alt="image" src="https://github.com/user-attachments/assets/f412bdc3-dcdc-4525-b33e-59655511cb48" />|
- tabIndex 적용을 위해 `margin-bottom`을 적용하니 StudioList 크기 계산에 문제가 발생
- `margin-bottom` 대신 새로운 `div`로 감싼 후 `padding-bottom` 적용
- 키보드 이벤트를 이용한 북마크 등록/해제 로직 구현 중... API 오류 발생!
<br>
> [QA] 스튜디오 아이템 margin 문제 해결

- src/pages/User/ChangePassword.tsx
- src/pages/User/ChangeProfile.tsx
- src/pages/User/PasswordConfirm.tsx
- src/pages/User/Profile.tsx
> #713 
<br>
- 내정보 관리 페이지 PC버전 UI 기능 구현
- 유저 개인정보 변경 페이지 PC 버전 UI 기능 구현
- 유저 개인정보 변경 페이지 버튼 `<Button text='다음' />` -> `<Button text='변경하기' />` 수정
- 비밀번호 확인 페이지 PC버전 UI 기능 구현 및 버튼 위치 버그 수정
- 비밀번호 변경 페이지의 PC 버전 UI 기능 구현
- 비밀번호 변경 페이지 버튼 위치 버그 수정
<br>
> [QA] 유저 정보 관리 페이지의 PC버전 UI를 구현하고 기존 적용된 UI 버그를 해결한다.

- src/pages/Home/Home.tsx
#702 
<br>
- 홈 부분 세션 lastpage 유무 체크 및 모달 추가
<br>
@JWJung-99  진욱님!
홈 부분에 로직 추가 한거여서 확인부탁드립니다!
> [QA] 예약전 로그인 후 원래 페이지 돌아가는 로직 추가

- src/components/ReservationCard/RatingReview.tsx
- src/components/ReservationCard/ReservationCard.tsx
- src/pages/User/MyPage.tsx
- src/types/types.ts
#503 
<br>
- 예약 카드 스타일 추가
- 예약 데이터 type 추가
<br>
@s0zzang 소정님!
리뷰 페이지에서 useGetReservationList훅을 통해 데이터 패치 후 ReservationCard에 데이터 넘겨줘서 사용해주시면 됩니다!
```tsx
const { data } = useGetReservationList('COMPLETED');
<ReservationCard data={data} />
```
@woojoung1217 우중님!
useLocation으로 상태값 받아와 사용하시면 됩니다!
현재 API에서 옵션 데이터가 없을 경우가 있어 옵션이 없을 경우 에러 방지 차원으로 스튜디오 이름과 메뉴 이름을 넣어놨습니다.
```tsx
const location = useLocation();
const { reservaionData } = location.state || {};
<ReservationCard data={reservaionData} isReviewWritePage={true} />
```
> [QA] 예약 카드 스타일 추가

- src/components/CopyButton/CopyLocation.tsx
- src/components/Kakao/KakaoMap.tsx
- src/components/Studio/StudioList.tsx
- src/pages/Reservation/ReservationCheck.tsx
- src/pages/Reservation/ReservationDetail.tsx
- src/pages/Reservation/components/ReservationInfo.tsx
- src/pages/search/SearchResult.tsx
> #693 
<br>
- 예약 상세 버튼 폭 너비 컨텐츠에 맞게 조정
- 예약 상세 구분선 너비 화면 전체 너비에 맞게 조정
- 검색 결과 시 스튜디오 리스트 갯수 반영
- 카카오맵 크기 조정 등
<br>
> [QA] 스튜디오 예약 상세 Ul 개선

- src/pages/Reservation/ReservationList.tsx
- src/pages/User/MyReviews.tsx
- src/styles/GlobalStyles.tsx
#719
<br>
- 인풋 포커스 스타일 변경 - 체크박스, 라디오버튼 스타일 정의
- 내 리뷰 페이지 - 헤더 고정
- 내 리뷰/예약 내역 - box-shadow 삭제, 하단 여백 조정
<br>
> [QA] 내 리뷰, 예약 취소 QA

- src/pages/User/BookmarkedStudios.tsx
- src/pages/User/MyPage.tsx
#717 
<br>
- 찜한 사진관 데이터가 없을 시 예외 처리
- 마이페이지 불필요한 import 제거
<br>
> [QA] 찜한 사진관 데이터가 없을 시 예외 처리

- src/components/Swiper/DimSwiper.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
#729
<br>
- 딤 스와이퍼 - 버튼 영역에 가려져 스와이프 미작동 오류 개선
- 딤 스와이퍼 - 모달 활성화시 페이지네이션 미노출 오류 개선
<br>
> [QA] 딤 스와이퍼 오류 개선

- src/pages/User/Auth.tsx
- src/pages/User/GoogleCallback.tsx
- src/routes.tsx
#351 
<br>
- 구글 로그인 api 적용 중
<br>
> [S4] 구글 로그인 작업 중

- src/pages/Reservation/ReservationList.tsx
#728
<br>
- 모바일버전 예약 내역 좌우 패딩 추가
<br>
> [QA] 모바일버전 예약 내역 좌우 패딩 추가

- src/components/Studio/StudioInfoDock.tsx
#733 
<br>
- StudioInfoDock 우측 여백 추가
<br>
> [QA] StudioInfoDock 우측 여백 추가

- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
#734
<br>
- 모바일 스튜디오 메뉴 상세 상단 여백 제거
<br>
> [QA] 모바일 스튜디오 메뉴 상세 상단 여백 제거

- src/components/Bookmark/Bookmark.tsx
- src/components/Navigator/ReservationNavigator.tsx
- src/components/ReservationCard/ReservationCard.tsx
- src/components/Studio/StudioItem.tsx
- src/pages/User/BookmarkedStudios.tsx
- src/pages/User/components/BookmarkedStudioItem.tsx
#735 
<br>
- StudioItem 마크업 변경 및 북마크 이벤트 버블링 방지
- 찜한 사진관 마크업 변경 및 탭 컨트롤 개선
- 찜한 사진관 이미지 object-fit 적용
- 예약 내역/내 리뷰 탭 마크업 변경
- 예약 카드 마크업 변경 작업 중
<br>
> [QA] 접근성 고려 마크업 변경

- src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
- src/pages/Studio/StudioMenu/StudioMenuDetailReview.tsx
- src/pages/Studio/StudioMenu/StudioMenuItem.tsx
#742 
<br>
- 메뉴 목록 타이포 수정, width 수정
- 메뉴 리뷰 페이지 이름 노출, 간격 수정
<br>
> [QA] 튜디오 메뉴 페이지 QA 반영

- src/pages/User/MyReviews.tsx
#639
<br>
- 마이페이지 내 리뷰 - 리뷰 작선 전, 후 구분
<br>
> [S4] 내 리뷰 - 리뷰 작성 전, 후 구분

- src/pages/User/components/BookmarkedStudioItem.tsx
#744
<br>
- 찜한 사진관 평점 소수점 첫째자리까지로 수정
<br>
> [QA] 찜한 사진관 평점 수정

- src/components/Bookmark/Bookmark.tsx
- src/hooks/useBookmark.ts
#745
<br>
- 북마크 설정/해제를 클릭했을 때 accessToken이 만료되어 403 에러 발생 시, 재 로그인을 유도한다.
<br>
> [QA] 북마크 403 에러 핸들링

- package.json
- src/components/ServiceAvailability/ServiceAvailability.tsx
- src/pages/Studio/StudioReview/StudioReview.tsx
- src/pages/Studio/StudioReview/StudioReviewWritePage.tsx
- src/pages/Studio/StudioReview/components/StudioReviewItem.tsx
- src/pages/User/Auth.tsx
> ex) #757 
<br>
-  이메일 로그인 사이즈, 아이템 화살표 제거 아이콘 사이즈 수정
<br>
> [QA] 이메일 로그인 사이즈, 아이템 화살표 제거 아이콘 사이즈 수정

- src/pages/Reservation/ReservationCheck.tsx
> #739 
<br>
- 배포환경시 예약자정보가 뜨지않는 문제 -> 복호화 코드 추가
<br>
> [QA] 예약상세 예약자정보 복호화 추가

- src/pages/Reservation/components/Payment.tsx
> #763 
<br>
- 결제요청시 accessToken 헤더 추가
<br>
> [QA] 결제요청 accessToken 헤더 추가

- README.md
#582 
<br>
- README.md 페이지 이미지 작업 중
<br>
> [Docs] README.md 페이지 이미지 작업 중

- tests/integration/Reservation.test.tsx
#772
<br>
- 테스트 코드 간결화
- 테스트 코드 mock reset
<br>
> [TEST] 예약 통합 테스트 코드 작성 - 고도화

- src/pages/Reservation/ReservationList.tsx
> Fix: 예약 건 수 카운팅 로직 수정
