package.json, pnpm-lock.yaml, src/components/Studio/StudioItem.tsx, src/components/Studio/StudioList.tsx, src/tests/Home.test.tsx, src/tests/StudioItem.test.tsx, src/tests/StudioList.test.tsx, src/tests/useGetStudios.test.tsx, src/types/types.ts, vite.config.ts
#75 
<br>
- `vite.config.ts`의 `test` 부분에서 타입 오류가 발생하여 수정
- Vitest(Jest)의 전역 함수 타입 오류를 방지하기 위해 `devDependencies`에 패키지 설치
- 스튜디오 로딩 시 맨 처음에만 로딩 컴포넌트를 표시하도록 수정
> **`isLoading` 시에 로딩 컴포넌트를 추가했더니 문제 발생**
> - 로딩 컴포넌트로 인해 가상화한 요소의 스크롤이 top으로 이동
> - 로딩 컴포넌트를 `Virtuoso` 안에 두었더니 로딩하는 동안 로딩 컴포넌트가 수없이 반복
> ⇒ 우선 맨 처음 로딩 시에만 로딩 컴포넌트를 표시하고, 이후 로딩 시에는 Skeleton UI를 사용하는 등의 방법을 고려 중
- 스튜디오 리스트 조회 결과가 없을 시 `EmptyMessage` 추가
- 스튜디오 제공 옵션 타입 추가
- 스튜디오 아이템 북마크 설정 여부 반영 ⇒ **api 나오면 연동 작업 남음**
- 테스트 코드 작성 및 테스트 통과 완료
- Home 컴포넌트
- StudioList 컴포넌트
- StudioItem 컴포넌트
- useGetStudios 훅
<br>
- @woojoung1217 @HuiseonDev @aksenmi @kyungmim @s0zzang 패키지 설치로 인해 `pnpm i` 한 번 부탁드립니다. …
=> [S2] 메인 및 하위 컴포넌트의 테스트 코드를 작성한다.

src/components/ImageSwiper/ImageSwiper.tsx
>  #98
<br>
- 한개용 이미지 슬라이드 방식 구현
- 기존 마우스휠 방식에 페이지네이션, 오토플레이 기능 추가
<br>
스튜디오 상세에서 쓰이는 이미지는 autoplay이랑 클릭 모두 작동되는 페이지네이션으로 만들어놨습니다. 
스튜디오 상세 페이지에서 slidesPerView={1} 를 설정하고, 적용할 스타일을 추가하시면 됩니다.
예시)
` <ImageSwiper images={['img1.jpg', 'img2.jpg', 'img3.jpg']} slidesPerView={1} imageStyle={custonImageStyle}/>`
=> [S3] 이미지 슬라이드 기능 추가 구현

src/hooks/useGetStudioDetail.ts, src/pages/Studio/StudioMain/StudioMain.tsx, src/styles/Common.tsx
> #150 
<br>
> 포트폴리오 미리보기 기능 구현
- 공통 컴포넌트 gray 여백 padding 적용
- 이미지 5개 이하라면 대체 이미지 적용
- query key 선언으로 데이터 캐싱, 자동 업데이트 적용
- studio id 가 존재하는 경우만 쿼리 실행
<br>
=> [S3] 스튜디오 상세정보 페이지 포트폴리오 미리보기 기능을 구현한다

src/components/Modal/Modal.tsx, src/components/Swiper/DimSwiper.tsx, src/pages/Studio/StudioPortfolio/PortfolioSwiper.tsx, src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx, src/pages/Studio/components/DimmedModal.tsx, src/store/useDimSwiper.ts, src/types/types.ts
> #191 
<br>
- 딤 모달 내 스와이퍼 기능 구현
- 딤 모달 스타일 변경 
- 포트폴리오 딤 모달 내 노출되는 데이터 변경 : 설명 -> 메뉴명
- 모달 닫기 버튼 z-index 변경
<br>
⬆️ 최대 3개만 담긴 스와이퍼 예시
- 포트폴리오 아이템을 클릭하면 딤 모달이 열리고 클릭한 아이템의 앞, 뒤를 포함한 최대 3개의 아이템만 스와이퍼에 담깁니다. 
- 스와이퍼가 3개씩 담기기 때문에 스와이퍼 페이지네이션을 사용할 수 없었습니다. 
따라서 현재 인덱스와 데이터 총 개수를 구하여 페이지네이션을 구현하였습니다.
- 포트폴리오 목록 데이터를 무한 스크롤 하는 경우는 반영되지 않았습니다. (ㅠ)
- 난이도가 있었던만큼 상세한 코드 리뷰 부탁드립니다 !
=> [S4] 딤 모달 내 스와이퍼 기능 구현 완료

src/components/Swiper/DimSwiper.tsx, src/pages/Studio/StudioPortfolio/PortfolioSwiper.tsx, src/pages/Studio/StudioReview/StudioReviewPhotos.tsx, src/pages/Studio/StudioReview/components/ReviewSwiper.tsx
> #267 
<br>
- 리뷰 모아보기 페이지에 딤 모달 스와이퍼 적용 완료
- 딤 모달 스와이퍼에서 사용하는 데이터 타입을 제네릭으로 변경
- 배포 버전에서 딤 스와이퍼 활성화 인덱스 미노출 오류 개선 (배포 확인해봐야 함)
<br>
@woojoung1217 님, 리뷰 모아보기 페이지에 딤 스와이퍼 적용 완료했습니다.
현재 이미지만 노출되는 상태이니 모달 내부 작업 부탁드립니다.
=> [S4] 리뷰 모아보기 페이지에 딤 모달 스와이퍼 적용

src/components/Navigator/ReservationNavigator.tsx, src/hooks/useGetReservationList.ts, src/pages/Reservation/ReservationList.tsx, src/types/types.ts
#306
<br>
- 예약 내역 조회 api의 response에 대한 타입 추가
- `IResvRes`
- 예약 내역 조회 결과에 대한 타입 추가
- `IResvItem`
- 예약 내역 조회 공통 useQuery 훅 수정
<br>
=> [S5] 예약 내역 조회 기능 추가

src/App.tsx, src/components/layout/Layout.tsx, src/routes.tsx
#420 
<br>
- `route.tsx` 구조 변경 - 기존 라우팅 경로들을 `children` 하위로 이동
- `ScrollToTop` 훅 호출 위치 변경`Layout` 컴포넌트 내부에서 `ScrollToTop` 훅 호출
<br>
- 소정님이 만드신 `useScrollToTop` 훅을 사용하였습니다. ([PR 참고](https://github.com/TEAM-FLASH/Toucheese-FE/pull/399/files))
- 기존에는 `RouteProvider` 외부에 `ScrollToTop` 훅을 배치하였습니다.
```tsx
<>
<BrowserRouter>
<ScrollToTop />
</BrowserRouter>
<RouterProvider router={router} />
</>
```
- `useLocation`이 `RouteProvider` 내부에 위치하지 않아 url 변경을 감지하지 못하는 문제가 있었습니다.
- 따라서`Layout` 컴포넌트 내부에서 `ScrollToTop` 훅을 호출하여 `RouteProvider` 내부에서 호출할 수 있도록 변경하였습니다.
```tsx
import ScrollToTop from '@hooks/useScrollToTop';
import { Outlet } from 'react-router-dom';
const Layout = () => {
return (
<>
<ScrollToTop />
<Outlet />
</>
); …
```
=> [QA2] 페이지 이동 시 스크롤 최상단으로 이동하지 않는 버그 해결

src/components/Swiper/ImageSwiper.tsx, src/pages/Home/Home.tsx, src/styles/GlobalStyles.tsx
#438 
<br>
- 슬라이드 양옆 여백 추가
- 스튜디오 리스트 상단 여백 변경 (9.6rem -> 10.8rem)
- img 태그에 하단 여백이 생겨 vertical-align:top 추가
<br>
@aksenmi 지민님! 
슬라이드의 오른쪽 영역이 레이아웃을 뚫고 나오다보니, 포트폴리오가 없는 경우(멋진 사진 준비중)와 레이아웃이 깨진다고 생각이 들었습니다.
따라서 가상 요소로 그라디언트를 추가했습니다! (아래 이미지 참고)
디자인팀과 상의 후 자유롭게 삭제하셔도 됩니다 !
그라디언트 없음 | 그라디언트 있음 (현재 상태) | 
| - | - |
| <img width="300" alt="image" src="https://github.com/user-attachments/assets/3bcd1340-894f-4f3a-bb6a-448388f9b5bc" /> | <img width="300" alt="image" src="https://github.com/user-attachments/assets/1c4b7c8f-602a-4bb2-9dca-7fc51bcb51bb" />
@woojoung1217 @JWJung-99 @HuiseonDev @aksenmi @kyungmim 
이미지 태그를 사용시 생기는 하단 여백을 방지하기 위해 이미지 태그에 수직 상단 정렬 …
=> [Q2] 이미지 슬라이드 양쪽 여백 추가

src/components/Swiper/ImageSwiper.tsx
#441 
<br>
- ```ImageSwiper```  pagination 스타일 수정
- ```ImageSwiper``` pagination 스타일 오류 해결
<br>
@aksenmi 지민님! 확인 부탁드립니다!
- **문제**
이전에 말씀드린 스타일 중복이 문제가 아니였더라구여! 원인을 찾아보니 CSS 우선순위로 인해 Swiper의 기본 스타일이 Emotion 스타일보다 우선 적용되어서 스타일이 틀어졌던거였습니다!
- **해결**
아래 코드 보시고 이해 안가시면 말씀주세요!
``` js
<Swiper className="imageSwiper"> // swiper 유니크한 클랙스 적용으로 우선순위 높이기
// 위에 유니크한 클래스를 추가하는 것만으로는 해결되지 않아서  Swiper의 기본 클래스를 추가하여 우선순위를 높였습니다!
& .swiper-pagination.swiper-pagination-horizontal {
position: absolute;
z-index: 10;
bottom: 15px;
left: 50%;
width: 8rem;
display: flex;
justify-content: center;
transform: translateX(-50%);
& .swiper-pagination-bullet {
background-color: …
```
=> [QA2] ImageSwiper pagination 스타일 오류 이슈 해결

src/pages/Studio/StudioPortfolio/StudioPortfolio.tsx, src/styles/BreakPoint.tsx, src/styles/Common.tsx, src/styles/GlobalStyles.tsx, src/styles/Variables.tsx
#463 
<br>
- PC 레이아웃 설정
- PC용 Common 변수 정의 : PCLayout, bg100vw
- 포트폴리오 상단 여백 변경 : 5.6rem -> ${variables.headerHeight}
<br>
다음과 같이 변수를 사용해서 값을 변경하고 사용하면 됩니다.
- 변수 설정할 때 : css 변수를 활용해 mo, pc 값을 변경 (GlobalStyles.tsx)
- 변수 사용할 때 : 이모션 변수를 활용해 변수 사용 `${variables.layoutPadding}`
-----
모바일과 다른 디자인을 적용하기 위해 pc 디자인을 적용할 땐 다음과 같이 사용합니다.
`${breakPoints.pc}` 변수를 통해 1024px을 설정했습니다. 
추후 분기점이 수정되면 한 번에 변경을 위함이니, 꼭 변수를 사용해서 반응형 작업을 해주세요 !
```tsx
export const breakPoints = {
pc: '1024px',
moMax: '1023px',
};
```
```tsx
body {
// 어쩌구 저쩌구 모바일 스타일 적용
@media (min-width: ${breakPoints.pc}) {
// pc 스타일 적용
}
}
```
-----
PC 스타일을 편리하게 작업하기 위해 공통 스타일을 정의하였습니다.
- PCLayout : …
=> [WEB1] PC 반응형 설정

src/components/FilterPriceSlide/FilterPriceSlide.tsx, src/components/FilterPriceSlide/FilterPriceSlidePC.tsx, src/components/Input/Input.tsx, src/components/ServiceAvailability/ServiceAvailability.tsx, src/hooks/useStudioReviews.ts, src/pages/Home/Home.tsx, src/pages/Home/components/PCFilterWrapper.tsx, src/pages/Studio/StudioReview/StudioReview.tsx, src/pages/Studio/StudioReview/StudioReviewPhotos.tsx, src/pages/Studio/StudioReview/StudioReviewWritePage.tsx, src/pages/Studio/StudioReview/components/StarInput.tsx, src/pages/Studio/StudioReview/components/StudioReviewImageList.tsx, src/store/useFilterStore.ts
> ex) #475
<br>
> PC에서 가격 섹션 부분 기능 변경으로 인한 분리 
- 모바일에서는 각자 초기화나 적용하기 기능이 있지만 PC에서는 일괄로 처리함 
- 선택된 요소를 useFIlterStore를 통해 선택된 요소 저장 후 URL를 통해 값이 변경 되도록 구현
- HOME에 있던 요소를 PCFIlterWrapper로 분리 
<br>
=> [WEB1] 반응형 가격 세션 구현 PC 작업 공유

src/pages/Reservation/ReservationCanceled.tsx, src/routes.tsx
#489 
<br>
- 예약 취소 후 예약 id를 웹 스토리지에서 받지 않고 경로에서 추출하는 방식으로 변경하였습니다.
- API가 완성되면 해당 id를 이용하여 예약 상세 내역을 fetch 하여 불러올 예정입니다. (현재는 임시)
<br>
@s0zzang 취소 후 `/reservation/_id(예약 id)/canceled` 경로로 보내주시면 됩니다요
=> [S5] 예약취소 완료 화면 id 추출 방식 변경

src/components/ReservationFooter/ReservationFooter.tsx, src/components/Toast/Toast.tsx, src/pages/Home/Home.tsx, src/pages/Studio/StudioMenu/StudioMenuDetail.tsx
#525 
<br>
- PC 버전 토스트 구현
- 메뉴 상세에서 로그인 하지 않은 상태로 예약하기를 눌렀을 때 => 로그인 => 메뉴로 돌아가는데, 이 때 홈화면으로 이동할 때마다 다시 메뉴 상세로 튕겨나가는 버그 해결
1. 로그인 안 된 상태로 예약하기를 누르면
`1-1. 로그인 페이지로 보낸다.`
`1-2. 세션스토리지에 lastPage를 저장한다.`
2. 로그인하고 홈으로 라우팅되면
`2-1. lastPage가 있으면 해당 주소로 라우팅한다.`
`2-2. 세션스토리지에서 lastPage를 삭제한다.`
**=> 홈에서 라우팅 시킬 때 세션스토리지에서 `lastPage` 삭제**
<br>
@kyungmim 임시로 로직 바꿔두었으니 수정하세요~
=> [WEB2] PC 버전 토스트 구현

src/components/Header/PCHeader.tsx, src/components/Studio/StudioInfo.tsx, src/components/Studio/StudioInfoDock.tsx
#589
<br>
- 전체 너비 `42.4rem`으로 변경
- 상단 패딩 `2rem` 추가
- 주소 길어질 시 아이콘과 주소의 정렬이 깨지는 현상 방지
- 스튜디오 이름 길어질 시 `...` 처리
<br>
=> [WEB2] 스튜디오 상세 오른쪽 고정 영역의 너비 및 내부 스타일 수정

src/pages/User/ChangePassword.tsx, src/pages/User/ChangeProfile.tsx, src/pages/User/PasswordConfirm.tsx, src/pages/User/Profile.tsx
> #477 
<br>
- 비밀번호 및 유저 정보 변경 API 통신 구현 완료
- 비밀번호 및 유저 정보 변경 에러 발생시 Toast 출력
- 비밀번호 및 유저 정보 변경시 불필요한 핸들러 삭제
- 정보 변경 완료시 modal 출력 -> toast 출력으로 변경
- toast 중복 출력으로 인한 useRef 플래그 적용
<br>
=> [WEB3] 유저 정보 및 계정 정보 변경 기능을 구현한다.

src/components/ReservationFooter/ReservationFooter.tsx, src/pages/Home/components/SelectTime.tsx, src/pages/Reservation/ReservationCheck.tsx, src/pages/Reservation/ReservationSchedule.tsx, src/pages/Reservation/components/ScheduleInner.tsx, src/pages/Studio/StudioMenu/StudioMenuDetail.tsx, src/pages/Studio/StudioMenu/StudioMenuDetailInfo.tsx
#634
<br>
- 예약 PC 레이아웃 변경 (flex -> sticky) : 스크롤 바 위치 변경(하위 콘텐츠 스크롤 -> body 스크롤)
| 변경 이전 | 변경 이후 |
| - | - |
|  <img width="1036" alt="image" src="https://github.com/user-attachments/assets/2bc5e754-74bc-47db-99d8-622948e86d78" />  | <img width="1054" alt="image" src="https://github.com/user-attachments/assets/b2f96f7e-5699-4f2e-9642-6d27794d7843" />
- 예약 PC 레이아웃 content-box 최소 높이 지정 : 메뉴 상세 고려
- 예약 PC 레이아웃 메뉴 상세 적용
<br>
@aksenmi 지민님 레이아웃 스타일 변경으로 불필요한 스타일 선언 삭제했습니다.
<br />
@kyungmim 경민님 메뉴 상세에 예약 PC 공통 레이아웃을 적용하였으니 확인 부탁드립니다.
추가로 모바일에서 아래의 오류가 발생하여 `aspect-ratio` 설정하였습니다.
=> [WEB3] "메뉴 상세 - 예약 스케줄 선택 - 예약 결제" PC 레이아웃 개선 및 통일

src/components/Navigator/ReservationNavigator.tsx, src/components/ReservationCard/ReservationCard.tsx, src/pages/Reservation/ReservationList.tsx, src/pages/User/MyReviews.tsx, src/utils/sortReservations.tsx
#639 
<br>
- 제네릭 타입 적용 및 전달
- 스타일 export
- 예약 내역 정렬 유틸 분리
- UI 구현
- 예외처리 - 로그인 세션 만료 안내
- 예약카드: 스튜디오 이름, 예약 일시 헤딩 태그로 변경 (h3, h4)
<br>
@JWJung-99 진욱님, 예약 내역 페이지 추상화를 진행하였습니다. 확인 부탁드립니다.
@kyungmim 경민님, 예약 카드 내 태그 변경하였습니다. 확인 부탁드립니다.
=> [S5] 내 리뷰 페이지 UI 및 반응형 구현

src/pages/Reservation/ReservationList.tsx, src/pages/User/BookmarkedStudios.tsx, src/pages/User/MyPage.tsx, src/pages/User/MyReviews.tsx
#659
<br>
- 403 에러로 로그인 페이지 이동 시 발생하는 토스트 렌더링 경고 해결
- 페이지 렌더링 중 `openToast`를 호출해서 발생하는 문제로, `error`를 의존성 배열에 담은 `useEffect`를 사용해 렌더링 이후에 `Toast`의 상태를 변경하도록 수정
<br>
=> [Hotfix] 403 에러로 로그인 페이지 이동 시 발생하는 토스트 렌더링 경고 해결

src/components/BookingSearchContainer/BookingButton.tsx, src/components/Header/PCHeader.tsx, src/components/Studio/StudioItem.tsx, src/pages/Home/Home.tsx
#658
<br>
- 필터 영역 `280px`로 변경에 따라 검색창 / 테마 탭 / 스튜디오 목록의 정렬 수정
- 이미지 크기 `width: calc((100% - 12px) / 7); aspect-ratio: 127 / 160;` 수정을 통해 이미지 영역의 뷰포트 초과 방지
<br>
- @s0zzang 필터 영역 너비를 `27.4rem`에서 `28rem`으로 변경했습니다. 변경 내용 확인 부탁드려요!
=> [WEB1] PC버전 필터 영역 변경으로 인한 컨텐츠 정렬

src/components/Studio/StudioInfoDock.tsx, src/pages/Studio/StudioDetailLayout.tsx, src/pages/Studio/StudioMain/StudioMain.tsx
#683
<br>
- StudioInfoDock의 높이 지정
- PC 헤더와 StudioInfoDock의 z-index 수정
- 스튜디오 상세 페이지 진입 시 발생하는 무한로딩 문제 해결
- 기존 세션 스토리지에서 data를 호출하는 방식은 Strict 모드가 아닌 배포 버전에서는 동작하지 않아 문제 발생
- React-Router Outlet이 제공하는 `context`에 data를 props 형태로 전달하고, 하위의 `StudioMain` 컴포넌트에서 `useOutletContext`를 활용해 data를 받아서 사용
<br>
=> [QA] 스튜디오 상세 페이지 진입 시 발생하는 무한로딩 문제 해결

src/pages/Home/Home.tsx, src/pages/Reservation/ReservationList.tsx, src/pages/User/BookmarkedStudios.tsx, src/styles/GlobalStyles.tsx
#681 
<br>
- PC버전 전체 레이아웃 하단 여백 `3rem` 추가
- 홈, 예약 내역, 찜한 사진관 등에서 부여한 하단 여백 삭제
<br>
@woojoung1217 @HuiseonDev @aksenmi @s0zzang @kyungmim PC버전 전체에 하단 패딩 `3rem` 추가하였으니 혹시 개인적으로 주신 분들은 삭제 바랍니다
=> [QA] PC버전 전체 레이아웃 하단 여백 추가 및 그에 따른 기존 여백 삭제

src/components/Button/Button.tsx, src/components/Filter/Filter.tsx, src/components/Filter/FilterSort.tsx
> #708 
<br>
- 버튼 공통 컴포넌트의 gap 사이즈 커스터마이징 기능 추가
- PC 필터링 정렬 버튼의 드롭다운 박스 간격 적용
- MO 필터링 버튼의 내부 아이콘 gap 사이즈 수정
<br>
-  @woojoung1217 @JWJung-99 @aksenmi @s0zzang @kyungmim 
버튼 컴포넌트에 아이콘과 텍스트 `gap`사이즈 커스터마이징 기능 적용해두었습니다! 아이콘이 있는 경우 텍스트와 기본 `gap` 사이즈는 `0.8rem` 입니다. 수정이 필요하신 분들은 `iconGap="0.5rem"` 형태로 `prop` 하시면 됩니다!
=> [QA] 필터링 정렬의 UI를 개선한다

src/components/ReservationCard/ReservationCard.tsx
#735
<br>
- 예약 카드의 마크업을 `article` → `a` 태그로 변경해 탭 컨트롤 활성화
- ReservationCard
- EmptyCard
<br>
=> [QA] 예약 카드 마크업 변경

src/pages/User/AuthVerification.tsx, src/pages/User/GoogleCallback.tsx, src/pages/User/KakaoCallback.tsx, src/pages/User/signupSuccess.tsx, src/types/types.ts
#351 
<br>
@woojoung1217 
- 카카오 로그인 실행 시
- 처음 가입하는 계정이라면 `/user/Authverification`으로 이동하여 본인인증 후 가입처리
- 이미 가입한 계정이라면 `userStore`에 데이터 저장 후 로그인처리
@HuiseonDev 
- Authverification에서 **다음**버튼 클릭 시
- 소셜 회원가입이라면 회원 가입 api 호출 후 성공 시 `/user/signupSuccess`로 이동
- 이메일 회원가입이라면 `/user/signup`으로 이동
=> [S4] 소셜 로그인 로직 추가

src/pages/Reservation/ReservationList.tsx, src/pages/User/MyPage.tsx
#766 
<br>
- `ReservationList`
- 이용 예정 예약 내역에서, 이미 날짜가 지난 예약 내역은 렌더링 하지 않는 것으로 로직 변경
- `MyPage`
- 마이페이지 레이아웃 수정
- 마이페이지 예약 내역 스와이퍼 슬라이드 개수 분기 처리
- `isPc === true`
- 예약 확정 데이터가 있다면 3개
- 데이터가 없다면 1개 (사진관을 예약해보세요!)
<br />
|데이터가 있을 때|데이터가 없을 때|
|:--:|:--:|
|<img width="1223" alt="image" src="https://github.com/user-attachments/assets/414a0040-dbe7-4e27-987d-af7d6b510e83" />|<img width="1215" alt="image" src="https://github.com/user-attachments/assets/90ab0f7f-e3be-4a0d-ab40-d2bb2653787b" />|
- `isPc === false`
- 1개
<br />
|모바일|
|:--:|
|<img width="293" alt="image" src="https://github.com/user-attachments/assets/9d287b06-47fe-4b1a-bf18-3b297df3db9c" />|
<br>
=> [QA] 예약 관련 스타일 및 로직 수정

src/pages/User/AuthVerification.tsx, src/pages/User/GoogleCallback.tsx, src/pages/User/KakaoCallback.tsx, src/pages/User/components/SocialCallback.tsx
#760 
<br>
- `Authverification` (@HuiseonDev)
- 소셜 회원가입 시 "인증하기" 버튼을 클릭하면 `/user/signupSuccess` 페이지로 이동하는 문제 발생
∵ `handleAuth` 함수의 response가 오기 전에 `handleSave` 함수가 호출되기 때문
⇒ `isVerified` 상태를 추가하여 `handleAuth` 함수의 response가 success일 때만 `true`로 변경하고, `isVerified`가 `false`라면 `handleSave`를 `return`하도록 변경 
- `KakaoCallback`과 `GoogleCallback` 코드가 거의 유사하여 `SocialCallback` 공통 컴포넌트를 생성하고 `type: "kakao" | "google"`을 이용하여 구분
<br>
=> [QA] 소셜 로그인/회원가입 로직 수정
